### ISSUE TITLE
Can I refresh OAuth Access Tokens?

### ISSUE THREAD

**Issue by futaz** [unitedworldwrestling/arena-public#10]
**Which application you are interested about**
REST API of Arena v1.5.53

**Your question**
I use this request to get az OAuth Access Token: `curl --request GET --url 'http://localhost:9080/oauth/v2/token?grant_type=https://arena.uww.io/grants/api_key&client_id=[my_client_id]&client_secret=[my_client_secret]&api_key=[my_user_api_key]'`

The response is something like this:
```json
{
  "access_token": "****",
  "expires_in": 86400,
  "token_type": "bearer",
  "scope": "read",
  "refresh_token": "***"
}
```

So it contains a refresh token. As I know, the standard way of refreshing tokens is something like this: `curl --request GET --url 'http://localhost:9080/oauth/v2/token?grant_type=refresh_token&client_id=[my_client_id]&client_secret=[my_client_secret]&api_key=[my_api_key]&refresh_token=[refresh_token_from_above_request]'`. (Note that the grant type is `refresh_token`.)

If this standard way works, then I don't have to deal with token expiration in my application, because the framework can handle it by sending a refresh token request. Only I have to do is setting a URL for this.

So is there a URL for refreshing oauth tokens? The example above does not work, it says:
```json
{
  "error": "unauthorized_client",
  "error_description": "The grant type is unauthorized for this client_id"
}
```

Alternatively, if there is no support for refreshing oauth access tokens, is there a way to test my solution for re-fetching auth tokens? I mean, can I somehow expire freshly fetched tokens to see whether my code for re-fetching works or not? It's not practical for me to wait until it expires, because it is 24 hours.

**Comment by csabavirag** [comment]
Arena does not support the refresh_token grant type, it's not accepted through the authentication endpoint so you can't use it to renew your access token at the moment.

However for development/testing purposes, you can use the following file along with the arena_upgrade tool [arena_commands_clearOauth.txt](https://github.com/unitedworldwrestling/arena-public/files/5866637/arena_commands_clearOauth.txt). This command will clear your OAuth tokens, so an access token on the client will not exist on the server anymore, thus the client application will receive a 401 Unauthorized error ("_The access token provided is invalid._").

Just download this commands file to the same dir where your arena_upgrade app is and rename it to `arena_commands.txt`.

**Comment by futaz** [comment]
Hey, thanks for the solution! I will try it soon and give you feedback, but now I have to deal with other tasks on my project.

**Comment by futaz** [comment]
I've tried the clearOauth.txt command and it worked. Thank you!
