### ISSUE TITLE
Enhancement: .ods support

### ISSUE THREAD

**Issue by theswix** [unitedworldwrestling/arena-public#101]
**In which application you miss a feature**
Arena

**Is your feature request related to a problem? Please describe.**
Wihle MS Office is the mainstream, some limitations regarding the product cost are really vibrant. There are some alternatives, including Google Sheets and LibreOffice Calc (both use .ods as internal spreadsheet representation) which provide the same functionality as MS Excel while being more affordable and having no issues with .xlsx compatibility in our case with Arena, which requires in fact pretty simple spreadsheet with no formulae etc

**Describe the solution you'd like**
In the long-term perspective to introduce .ods support in Arena for importing the external data

**Describe alternatives you've considered**
None

**Comment by csabavirag** [comment]
You can try it out via the beta channel now.

**Comment by theswix** [comment]
Works perfectly. Thank you!
