### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by behzadbadr** [unitedworldwrestling/arena-public#102]
Hello
In some competitions that are held, it is not possible to change the name of the team, and in some competitions, team to team, it is not possible to draw the teams. The matches cannot be reinstalled, please follow up
Thankful

**Comment by csabavirag** [comment]
Do you receive an error when trying to change the name of the team?
Could you please detail the problem with the necessary steps to reproduce the problem?

**Comment by behzadbadr** [comment]
We have the problem of filtering foreign sites here, and for this reason, the internet is disconnected and with vpn, it is difficult to download.
Please make a zip version available if possible

**Comment by behzadbadr** [comment]
Due to the problem of internet and the difficulty of updating Arena in Iran, I would like you to make a new version available in the form of a zip file so that we can use it in Iran, or send it to my Gmail address.
Thankful
[behi.badr18@gmaill.com](mailto:behi.badr18@gmaill.com)
