### ISSUE TITLE
Scoreboard match list for more than 1 competition

### ISSUE THREAD

**Issue by palvespt** [unitedworldwrestling/arena-public#104]
**Which application you are interested about**
[eg. Arena, Scoreboard, LGTV, etc]

**Scoreboard**

**Your question**
Hi UWW team,

Is it possible to  get the match list from 2 different ARENA competitions ?
E.g Competition 1 with MAT A and B
      Competition 2 with MAT C or D or both

Or do i need to have another VM with other Arena instance for the second competition?

Thanks in advance for your support.

Pedro Alves

**Comment by csabavirag** [comment]
Please check Scoreboard version 1.2.37.16. There is a new feature about selecting a specific event at Load Matches menu.
I don't really understand the requirement of managing fights from Competition 1 Mat A+B in a single instance of Scoreboard, when it is dedicated to a specific mat.
If you want to combine fights from multiple mats, you must collect those fights under a Mat in Arena (Sessions tab) - eg. collect all fights to Mat A in Arena - and set Scoreboard for that Mat (Mat A).

Also, for Competition 2, collect those fights to the same Mat name (Mat A) and Scoreboard will pick them up automatically (or can filter for Competition 2 in Load Matches).

If I understood your question wrong, please provide more details.

**Comment by palvespt** [comment]
Hi Csaba,
I already checked the Scoreboard version 1.2.37.16 and you solved my problem with this feature.
Regarding my issue, i´m sorry i didnt explained correctly. Let me explain in another way. 

2 different competitions on the same day and same FOP;
Competition A = Championship for seniors between 4 teams or more;
Competition B = Other competition for cadets, juniors, young kids etc;

Mat A & B for Competition A;
Mat C or D or both for Competition B .

Before your update i created the Competition A and B on Arena but i couldnt get the fights from the 2 competitions (not sure if i was doing something wrong).
Now im able to pull all matches from both competitions.
Thank you for that.

Now my suggestion is, instead of having all the events listed on the listbox, the user should get the last 5. This will prevent the size of the listbox to get very big.

Finally i would like to say thank you again for your amazing suport!
Cheers!

**Comment by palvespt** [comment]
Thanks again Csaba!
