### ISSUE TITLE
Arena не обновляется

### ISSUE THREAD

**Issue by Oralkhan55** [unitedworldwrestling/arena-public#105]
**Which application you are interested about**
[eg. Arena, Scoreboard, LGTV, etc]

**Your question**
Здравствуйте! Не могу обновить на более новую версию Arena.

**Comment by euhenpetrov** [comment]
Прояви уважение, пиши на английском. Тут никто необязан знать русский!!!

**Comment by Oralkhan55** [comment]
Sorry for my mistake, I did not know.
Best regards, Oralkhan
  
>Вторник, 13 декабря 2022, 15:05 +06:00 от euhenpetrov ***@***.***>:
> 
> 
>Прояви уважение, пиши на английском. Тут никто необязан знать русский!!!
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <unitedworldwrestling/arena-public/issues/105/1347975525 @ github . com> 
 
 
С уважением,
Sport SHIKOR
***@***.***

**Comment by csabavirag** [comment]
No problem. Please open a new issue in English (or check if there is a similar issue to your problem and write your comment there)

**Comment by Oralkhan55** [comment]
Thank you, problem solved!

  
>Вторник, 13 декабря 2022, 15:49 +06:00 от csabavirag ***@***.***>:
> 
> 
>No problem. Please open a new issue in English (or check if there is a similar issue to your problem and write your comment there)
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <unitedworldwrestling/arena-public/issues/105/1348077662 @ github . com> 
 
 
С уважением,
Sport SHIKOR
***@***.***
