### ISSUE TITLE
Arena 1.5.84.1 update problem 

### ISSUE THREAD

**Issue by dkaya60** [unitedworldwrestling/arena-public#106]
Dear Csaba :
While updating 1.5.84.1 in the arena, when it reaches 6%, the update does not continue. Is this problem caused by me? Or general update problem can you help? thanks

**Comment by dkaya60** [comment]
![arena 1 5 84 1](https://user-images.githubusercontent.com/79795576/206899886-6f9002be-7a78-4929-8206-92330a9eeaf0.png)

**Comment by palvespt** [comment]
Hi Dursun,
To me it happened at 86%. 
Then after 10 minutes i closed the browser but the update was already completed with no issues.
Current version is 1.5.84.1
Hope it helps.
Pedro

**Comment by dkaya60** [comment]
Hello Palvespt,
unfortunately I tried a lot today but the update 1.5.84.1 is not installed. It does not go beyond 6%.

**Comment by behzadbadr** [comment]
Hello
In Iran, I have the problem of updating version 1.5.83.1 and higher versions
Please send me if possible

**Comment by csabavirag** [comment]
Sorry to hear that. That seems to be a network issue while downloading the new version. 
To know more about the error, it would be nice to see the output of the failed upgrade job from http://localhost:8080/jobs

**Comment by behzadbadr** [comment]
Hello
If possible email me a zip file of the latest version
thank you


‫‪csabavirag‬‏ ***@***.***‬‏> در تاریخ دوشنبه ۱۲ دسامبر ۲۰۲۲
ساعت ۱۲:۲۱ نوشت:‬

**Comment by csabavirag** [comment]
@behzadbadr a version upgrade is not just about copying "some" files to their destination, but it does several other things. Thus it is not possible to create a "zip" file and share with those who had network connectivity issues.
Send a mail to the IT@uww mailbox and we can discuss how to troubleshoot you remotely. @dkaya60 you may want to drop a mail as well.

**Comment by csabavirag** [comment]
Closing
