### ISSUE TITLE
Increasing  number character names in the scoreboard

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#107]
Hi
Dear Mr. csaba, if is it possible, the number of first and last name characters which is displayed on the scoreboard increase to 22 characters. In addition, taking into account that Persian is written from right to left, therefore, changing the position of the dot (point) at the end of  the last name is requested. Also, if it is possible, action should be taken to change the font of the scoreboard (#61)
![DOT](https://user-images.githubusercontent.com/82810245/207572514-eb7a11f5-8024-4f96-80a8-3576cf80340f.jpg)

**Comment by csabavirag** [comment]
Hi Mostafa, the dot at the "end" of the name is coming from Arena, you should expect an update with one of the next releases.
It also needs to be evaluated how flexible Scoreboard can be in terms of displaying longer names.
Give us some time to look into that. Thanks!

**Comment by csabavirag** [comment]
@mostafaaghayari what about the text direction? The Persian order is RightToLeft, are the names displayed properly?
Or that should also be converted? This screen shows the name in right to left order (Nasiri M.) if it was converted properly :)
![image](https://user-images.githubusercontent.com/10976654/208130204-1ae42163-ac28-41f0-b932-c94d29de53be.png)

**Comment by mostafaaghayari** [comment]
ذخیره کردن ترجمه
Hi
 Dear Mr. csaba,
  Yes, thanks, the directions shown on both screens are correct.
![scor1](https://user-images.githubusercontent.com/82810245/208285825-f435b7a9-4719-489e-af50-1bc967b52d7e.jpg)

**Comment by csabavirag** [comment]
Hi Mostafa, can you also confirm that the name on the screenshot I pasted above is also correct?
In addition to that, what about the text alignment of the Blue wrestler. Should that be aligned to right?
Like this:
| . نصیری م &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;. نصیری م |
| ----- | ----- |

**Comment by mostafaaghayari** [comment]
Hi Dear Mr. csaba,
Yes that's right
Blue and red should be aligned from the right side.

**Comment by mostafaaghayari** [comment]
Hi
Dear Mr. csaba, Please advise regarding items #51 and #89

The problem related to team competitions (more than two groups)#51. (#51
has been closed by mistake(

 challenge system and connect them to the scoreboard #89.

**Comment by csabavirag** [comment]
Hi Mostafa, perhaps I was not clear enough with my question or just not sure if I got the expected answer :). So that's ok to display the names starting from right to left. But which one is the desired alignment from the combinations below?

|  |  |  |
| -- | -- | -- |
| 1. | . نصیری م                  |                 . نصیری م|
| 2. | . نصیری م                  |. نصیری م                  |
| 3. |                 . نصیری م | . نصیری م                 |
| 4. |                 . نصیری م |                 . نصیری م|

**Comment by mostafaaghayari** [comment]
Hi Dear Mr. csaba,alignment #4
thanks.

**Comment by Artem19qq** [comment]
hello! help me please! how to create account for arena? after install uww arena need to enter login and parol. where i can find this login and password? thank you

**Comment by Artem19qq** [comment]
I don't know what to do next???

**Comment by csabavirag** [comment]
Dear @Artem19qq, I created a dedicated issue (#146) for your problem, because your question is not related to opener's question at all. Please use that issue to raise any further question about login
