### ISSUE TITLE
VirtualBox error

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#109]
Hi
Dear Mr. csaba, Please guide me to fix the following error
(Version 1.5.82)
![error](https://user-images.githubusercontent.com/82810245/208290088-0b423243-c40b-44f0-a2bc-31304d18fc87.jpg)

**Comment by csabavirag** [comment]
As I can see in this ticket https://www.virtualbox.org/ticket/17640 you should check the VBoxHardening.log file to find which (most likely) .dll file is related to this problem (marked as "rejecting").
I also found some article, which mention that the use recently installed/updated a completely different application on their computer which had no digital signature and VirtualBox did not tolerate that.
Check the logfile to get closer which module blocks the start of VirtualBox and/or think about what you installed recently (and consider to uninstall).

**Comment by mostafaaghayari** [comment]
Thank you very much
