### ISSUE TITLE
Referees level

### ISSUE THREAD

**Issue by palvespt** [unitedworldwrestling/arena-public#113]
**In which application you miss a feature**
Referees

Dear UWW Team,

In PT we have more categories then those that are presented on the ComboBox, like Trainee, Regional, and National.

So if possible can you please add also these categories to Arena?

Trainee
Regional
National

Thanks in advance for your support.

Pedro 

![referees](https://user-images.githubusercontent.com/94856801/212783818-c88b55de-eecb-4bc0-b76f-59ea0e972e20.jpg)

**Comment by palvespt** [comment]
Dear UWW team,

Is it possibible to add the Referees categories above ?

Thanks in advance for your support.

Pedro

**Comment by csabavirag** [comment]
Hi Pedro,
Please give us some time to work on your request. Will update this issue once we have made progress on it.

**Comment by theswix** [comment]
> Hi Pedro, you can get this feature started from Arena version 1.5.86.
> 
> Just go to Sports Config and enter as many as you want in the format the example shows to you.
> 
> ![image](https://user-images.githubusercontent.com/10976654/230125892-83731931-7f32-4db2-af5a-07268c5ec81e.png)

Super! Thank you for wonderful job, as usual :)

**Comment by palvespt** [comment]
Dear Csaba,

Thanks for your support.

Quick note: I was able to update the systema for the last version (1.5.86.) however i hve an issue on the configuration.

![issue system setting_referee](https://user-images.githubusercontent.com/94856801/233094422-3263d4e0-1998-4ffb-a853-dc2f82668b50.JPG)

Is it on my side?

Thanks 
Pedro

**Comment by csabavirag** [comment]
Hi Pedro,

Sorry, it's not your fault. There is a formatting problem with the Insert an example option.
Please ident the referee block under system like this:
```
system:  <--- we need the system container
    referee:
        customLevels:
            - Trainee
            - Regional
            - National
```

**Comment by palvespt** [comment]
Hi Csaba,

I see....it´s kind of a class.

It works perfectly now!

Many thanks for your support!
