### ISSUE TITLE
D CUSHION LOOKING IN 4 CUSHION COMPETITIONS

### ISSUE THREAD

**Issue by dkaya60** [unitedworldwrestling/arena-public#115]
Dear Csabavirag
In four-cushion competitions, the D mat stays on the far right of the page and the four mats are not visible at the same time. In order to see the D cushion, we need to use the spacebar at the bottom of the page. In multiple competitions, we 
have to come to the bottom of the page each time, this problem causes a waste of time. As a solution, if you put the space bar at the top of the page, it will still be more useful.

![1](https://user-images.githubusercontent.com/79795576/219480471-0817e271-bacb-4b60-b4db-c8e84436f2ce.png)
![2](https://user-images.githubusercontent.com/79795576/219480533-9556997d-e0c3-48e3-a37f-3169e6a8c1d7.png)

**Comment by dkaya60** [comment]
Another solution could be to bring the four cushions together so that we can see them at the same time.

**Comment by csabavirag** [comment]
Hello Dursun, that makes sense. Let us work out the 2nd scrollbar to the top. It will be available soon.

**Comment by dkaya60** [comment]
Thank you Csabavirag see you soon..

**Comment by csabavirag** [comment]
This feature is available starting from 1.5.85.6
