### ISSUE TITLE
EROR during sending match report from uwwtiming 1.2.38.4 to 1.5.85.3 arena

### ISSUE THREAD

**Issue by euhenpetrov** [unitedworldwrestling/arena-public#116]
**Which application you are experiencing a problem with**
[eg. Arena, Scoreboard, LGTV, etc]                                              arena 1.5.85.3 + uwwtiming 1.2.38.4

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, 
![Screenshot_1](https://user-images.githubusercontent.com/67595896/219946131-36cab07a-697f-408a-a20f-8aaf63ab417f.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/67595896/219946157-b196e28e-380d-4ded-9d20-8d589f949140.jpg)
add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]                                                                 w10
 - Browser [e.g. chrome, edge]                                                       chrome

**Additional context**
 Hello to all developers of arena and mr. Csaba! In my last turnament I have met with the next problem in using arena 1.5.85.3 and 1.2.38.4 uwwtiming, I can load matches from arena to the scoreboard and start match (green color match number in arena), also matches are active in onvenue screen. BUT when match is finished I have EROR wile sending math to arena from scoreboard. When I am trying to close match into arena I also have internal eror.

**Comment by csabavirag** [comment]
@euhenpetrov did you get this error with every single match or only for some of them? If just a set of matches failed, it would be nice to compare them with the good ones to see if those matches are specific to a property.

Can you reproduce the issue with another test event? If it's reproducible, please share the exact steps to get to the error.

**Comment by euhenpetrov** [comment]
Thanks for the answer! This error applied to the entire event I created.
But when I created a new test event the error went away. Also, when I
specified https://arena.uw.in.ua in the scoreboard settings, the error
disappeared. On the local arena, I have one unclosed match left, you can
see this error (the match does not close manually and the scoreboard does
not send a report).
  When I imported the excel file with the participants, the file was 99%
imported, then the arena hung. Then I saw in the excel file that I did not
indicate the age group and wrestling style of one of the participants.
Apparently, this led to a violation of the functionality of this particular
event. When I loaded the correct file, the import stopped at 100% but the
arena hung. Weight categories appeared when I clicked on the appropriate
button. After the draw, the matches did not appear in the "match schedule"
column. After rebooting the virtual machine, the matches were established,
but an error occurred in the hitch with the scoreboard.
Hope the information was helpful. With respect and gratitude. Eugen!

пн, 20 февр. 2023 г. в 14:44, csabavirag ***@***.***>:

**Comment by csabavirag** [comment]
Can you send me the output if the import command from `/jobs` list at your local Arena? The server's import command did not show any error. Although I did not expect any since you mentioned that worked well.

**Comment by euhenpetrov** [comment]
Thanks for solving the problem.
