### ISSUE TITLE
Can I run Arena VM in a KVM-based virtualized environment?

### ISSUE THREAD

**Issue by futaz** [unitedworldwrestling/arena-public#12]
**Which application you are interested about**
Arena 1.5.70

**Your question**
We have a KVM-based virtualized infrastructure, so the host machine where I want to install virtualbox for hosting Arena VM is itself a guest on KVM. The "intermediate" host, which is running virtualbox for Arena is an Ubuntu 20.04 server without GUI.

I can install virtualbox and import Arena-1.5.70.ova file. When I start Arena VM, from the point of view of virtualbox host, Arena VM starts successfully, but it is not available on http, even from localhost and according to the log files of virtualbox, Arena VM stops in the middle of the boot process.

We also have tried with NAT and bridged mode, but nothing happens.

Is it possible to run Arena in an environment like this? Do you have any experience in it? Can you suggest some config to make it work? Maybe some virtualbox features to switch off?

**Comment by csabavirag** [comment]
I don't have experience with this type of setup, but I would recommend to use the OVA file's content as disk directly on the KVM to configure a virtual environment and try to avoid the KVM->Ubuntu VM->VirtualBox->Arena VM approach. So simply KVM -> Arena VM.
Let us know if you had a chance to test this.

**Comment by futaz** [comment]
Our tech guy created a new virtual machine on the KVM host with similar configuration to the virtualbox VM created by the official ova file and attached the virtual disk from the ova file to this KVM guest. I think he had to convert the virtual disk to a format suitable for KVM, but finally it worked. Thanks! :)
