### ISSUE TITLE
Urgent problem  on nordic system-Arena

### ISSUE THREAD

**Issue by prosfygas33** [unitedworldwrestling/arena-public#121]
**Which application you are experiencing a problem with**
arena

**Describe the bug**
Hello. I Have arena  version 1.5.83.1 and my problem is in a group of 7 persons with nordic system , and the ranking was wrong. Why in system shows ΔΗΜΟΥ first and not ΠΑΠΑΚΩΣΤΑΣ. They have same wins, same points and in their between match ΠΑΠΑΚΩΣΤΑΣ win. The img attached shows my problem in raking.
![uww nordic problem](https://user-images.githubusercontent.com/52703745/233788722-28b12baa-0385-4ade-8342-def36baee16a.JPEG)

**Comment by alexkha73** [comment]
In a same group, if two wrestlers have an equal number of victories, their direct match will determine the 
ranking.
For all the other cases with a tie between athletes, the ranking will be determined following these criteria,
across the all competition:
- The highest classification points
- The highest victories by « Fall »
- The highest match victories by superiority
- The highest technical points scored
- The fewest technical points given
- The lowest seeds number (if applicable)
- The lowest draw number 
- The lowest draw number

**Comment by prosfygas33** [comment]
Hello again, thanks for your prompt response . 
However you still didnt answer to my question. If you notice the screen picture which I send to you. In the first group, 3 athletes had equal number of victories, but only 2 of them have same classification points, In their direct match the second athlete  ΠΑΠΑΚΩΣΤΑΣ(A4-203) win the first athlete ΔΗΜΟΥ(A1 -8). But in the bracket showed ΔΗΜΟΥ (A1-8)  first in ranking. So my question is why system showed first the athlete who lost in his direct match with his opponent? In printscreen you can see all the details.

This happened in a national championship and i came up with a awkward situation.
Thank you in advance.

**Comment by csabavirag** [comment]
You must interpret the relevant part of the rules book (that Alex copied into his answer) this way:

1. _In a same group, if <ins>**two wrestlers have an equal number of victories**</ins>, their direct match will determine the
ranking._ 
    - On your screenshot, in Group A there are **three** athletes with the same number of victories (2 victories per each **A1**, **A4** and **A2**), therefore this statement is not applicable to them
2. Thus you must continue the comparison with the remaining criteria list
    1. _The highest classification points_: **A1** and **A4** has equal number of classification points (C.Pts = 9)
    2. _The highest victories by « Fall »_: **A1** has 1 victory by fall in match # 41 (I assume that's a VFA - 5:0 against **A2**), while **A4** has no match ended by VFA

And we stop here, because **A1** has more victory by fall (VFA = 1) than **A4** (VFA = 0), thus he is ranked the 1st.

That's the reason why **A1** is ranked first.

**Comment by prosfygas33** [comment]
Good morning csabavirag , Thank you very much for your quick reply, you helped me again a lot.
