### ISSUE TITLE
Custom localization and UI translations

### ISSUE THREAD

**Issue by delros** [unitedworldwrestling/arena-public#122]
**Which application you are interested about**
Arena, Scoreboard, LGTV, etc

Hi team, 

Is there any possibility to contribute to a simplistic, but crucial area for usability level - localization and translation of the UI? As far as I understood, the solution is not opes-sourced, so it is not obvious if the community can help with this. Any feedback will be highly appreciated

Thanks,
Ernesto

**Comment by csabavirag** [comment]
Hi Ernesto,

Arena already supports localization, it has several (more or less) complete translation to different languages.
In terms of UWWTiming (Scoreboard), it's on our backlog.
If you would like to participate in extending Arena language support with a non-existing one, drop a mail to it@ mailbox please.

**Comment by delros** [comment]
@csabavirag, will do, thanks a lot for the feedback
