### ISSUE TITLE
Beach wrestling

### ISSUE THREAD

**Issue by prosfygas33** [unitedworldwrestling/arena-public#126]
**Which application you are interested about**
Arena

**Your question**
Good morning, I am a frequent customer. :P . I want to ask something, next weekend we have Hellenic national beach wrestling, and the person who organizes it informed me that there is a new rule that more than every coach during the tournament can only make 2 challenges, 1 in the first phase of the matches and 1 in the semi-finals-finals.  is something like that true?

**Comment by csabavirag** [comment]
That is correct. The 2023 rules of Beach Wrestling allow every athlete to have only 2 **lost** challenge. So the athlete can have as many challenge requests across the tournament until they won those challenges.

To have this feature available to your tournament, you must have Arena running on version at least 1.5.86. This version's changelog contains this:
```
1.5.86 / 2023-04-05
New: Beach Wrestling: Updated Weight Categories (Sports Config), 2nd Weigh in support, Challenge management according to 2023 rules
```

**Comment by prosfygas33** [comment]
Hello, thanks again for the information. Updated all programs to latest version (Arena, Scoreboard, LGTV). Everything seems fine except the transmission from LGTV, but I can't get the points to LGTV. I registered all the required credentials for the program (mat, IP, event type), but I just get a blank green screen. Everything was fine on my previous LGTV. Any solution for this?

**Comment by bouaziz1991** [comment]
Dear @prosfygas33 can you make sure 

1. Firewall is off
2. ping to scoreboard is fine
3. No activated Antivirus (can block the connection)
4. Run LGTV as administrator
5. make sure you select all fields (Event name, Mat setup, Branding, Streaming and Recording settings) and check **SEND SETTINGS** checkbox
if still you have an issue, please send us email to it@uww.org to make an ANYDESK session and fix the issue,
