### ISSUE TITLE
Arena in Docker Container

### ISSUE THREAD

**Issue by plastilincheg** [unitedworldwrestling/arena-public#127]
Due to the obsolescence of the Ubuntu host system currently used as the basis for the operation of the server part of the software, is it planned to change the concept to translate it into Docker or alternatives?

**Comment by csabavirag** [comment]
Where did you get from that Ubuntu is being marked as obsoleted?
Apart from that, it has already been discussed to provide an alternate operating framework to VirtualBox which is most likely Docker.

Would be nice to hear opinions (pros/cons) from all of you.

**Comment by plastilincheg** [comment]
OS obsolescence issue - conceptual, now active 20.04. Next, a new version will follow, the old one will no longer be accompanied. There will be a question of data transfer, which will lead to downtime and sometimes the inability to transfer them. Moving containers will not cause, in most cases, such problems IMHO

**Comment by csabavirag** [comment]
Hello, let's continue the discussion at https://github.com/unitedworldwrestling/arena-public/discussions/133
You may find it interesting
