### ISSUE TITLE
Double-elimination tournament

### ISSUE THREAD

**Issue by OviBurg** [unitedworldwrestling/arena-public#13]
Hi, 
in the internal competitions at children's level it would be nice to use double-elimination tournament brackets.
 thank you!

**Comment by csabavirag** [comment]
What do you mean double elimination? The most common bracket for young wrestlers is the so called "double bracket", but this this is for the repechage (all the opponents of the 4 of 1/4 finals winners go to repechage) and not the elimination. Do you think something different?

**Comment by OviBurg** [comment]
A system in which a defeated athlete has a second chance even if his winner has lost.
https://en.wikipedia.org/wiki/Double-elimination_tournament
![NSB-doubleelim-draw-2004](https://user-images.githubusercontent.com/74675113/107795718-b2907900-6d61-11eb-8c1c-46ddf52f1700.png)

**Comment by csabavirag** [comment]
Thank you for the details. Yes, at the moment Arena does not support such a bracket.
I mark it as an enhancement and we will update this issue when development starts.
