### ISSUE TITLE
Translation into Ukrainian

### ISSUE THREAD

**Issue by plastilincheg** [unitedworldwrestling/arena-public#130]
What files are needed for translation into Ukrainian?

**Comment by csabavirag** [comment]
Could you please send a mail to IT mailbox? We will contact with you shortly

**Comment by plastilincheg** [comment]
Wrote a letter...

**Comment by plastilincheg** [comment]
Translated. Waiting for testing

**Comment by csabavirag** [comment]
Arena version 1.5.89.4 is released with support of Ukrainian.
