### ISSUE TITLE
BW Scoreboard displays wrong advantage when caution given

### ISSUE THREAD

**Issue by tifiseu** [unitedworldwrestling/arena-public#132]
**Which application you are experiencing a problem with**
UWWtiming

**Describe the bug**
Scoreboard displays advantage to opponent when caution given, but athlete scored last

**To Reproduce**
1 point light
caution dark
1 point dark
-advantage is on light. because of caution
but in BW caution must not be accounted - only last score

**Expected behavior**
1 point light
caution dark
1 point dark
-advantage is on dark. because he got last point

**Comment by csabavirag** [comment]
Thank you for reporting the issue. We will work on it and fix.

**Comment by ybouaziz** [comment]
Hello,

This issue will be fixed on next version of UWWTiming.

Best regards!
