### ISSUE TITLE
Draw error

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#135]
Dear Mr. Csaba
Hello
In Taleghani Cup competitions, local random generator was used for draws, but unfortunately, in some weights where the number of athletes was more than 150, the draws were incomplete and in other weights, the draws started from 50. Please check .

https://github.com/unitedworldwrestling/arena-public/assets/82810245/83eff4c0-969b-409f-a3be-e807938a7899

**Comment by csabavirag** [comment]
Hi Mostafa, yes you were right. There was a limitation to 150 participants in the Local Random Generator.
Thanks for reporting this issue, in the next Arena version, it will be fixed.
