### ISSUE TITLE
Two Step Deletion

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#137]
Mr. Csaba, the weights, names or... may have been deleted from the system by mistake, so if possible, any deletion in the system should be done after user approval (two-step deletion). Please check and correct if possible.

https://github.com/unitedworldwrestling/arena-public/assets/82810245/3e6d77eb-c85b-4ecd-b7d2-98a926d167e1

**Comment by csabavirag** [comment]
Hi @mostafaaghayari your request completely makes sense.
Give us some time to extend the confirmation box to other parts of the system where those are not available at the moment.

**Comment by csabavirag** [comment]
Popups have been added to critical actions.
You can take a look on it by upgrading to Beta (or using Docker beta image) until it's published in the next Arena version.
