### ISSUE TITLE
Age Category for engaged list

### ISSUE THREAD

**Issue by harisandratra** [unitedworldwrestling/arena-public#14]
when i print the engaged list for the team i can't see the difference of age categorie (ie FS -57kg, and FS -57kg) i know that that mean FS JUNIOR -57kg, FS SENIOR -57kg but is it possible to print with there Age Categories to be not confused?

thank you

**Comment by csabavirag** [comment]
Please upgrade your Arena to 1.5.72 and check if the new feature serves your needs.
