### ISSUE TITLE
Beach Wrestling rules

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#141]
Hello, Mr. Csaba
In the update 1.5.89 dated 2023-06-07, the article Fix: In Beach Wrestling, medal match athlete has no ability for challenge if they have lost one during qualifications is mentioned, but I did not find the mentioned items in the rules of beach wrestling 2023. 
Thanks

[1.5.89 2023-06-07.pdf](https://github.com/unitedworldwrestling/arena-public/files/12562430/1.5.89.2023-06-07.pdf)

**Comment by csabavirag** [comment]
Hi Mosafa,

please see the regulation on challenges at Page 9 of the [Beach Wrestling Rules Book](https://cdn.uww.org/s3fs-public/2023-06/beach_wrestling_world_series_rules_en.pdf?VersionId=Sj5Oo8yerkzBoF9188XDYbBFfN_nZGNn)

> Each wrestler is entitled to two (2) challenges per event. One challenge during the group stage and the
> eliminations and another one challenge during the medal match. If after reviewing the challenge the
> refereeing delegate (or his substitute) modifies the decision in favour of the wrestler who requested for
> challenge, then the challenge can be used again during the event by the concerned wrestler.

I hope this describes the challenge behavior well enough.

**Comment by mostafaaghayari** [comment]
Hello and thanks
