### ISSUE TITLE
Update and backup in Docker

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#144]
Hello Dear Casba
      If possible, please guide how to update and backup in Docker.
       Thanks

https://github.com/unitedworldwrestling/arena-public/assets/82810245/289c9d69-7ade-4f3c-84e9-b737dcc849b2

**Comment by csabavirag** [comment]
Have you tried to follow the "Upgrading to a newer version" section at https://github.com/unitedworldwrestling/arena-public/discussions/133 ?

I close this question here. If you still experience problem, please submit it under the discussion https://github.com/unitedworldwrestling/arena-public/discussions/133

**Comment by mostafaaghayari** [comment]
Hello, Mr. csaba
Thank you very much for your guidance. If possible, please also advise on how to make a backup.

**Comment by csabavirag** [comment]
See my answer to your backup question under https://github.com/unitedworldwrestling/arena-public/discussions/133

**Comment by mostafaaghayari** [comment]
thank you very much
