### ISSUE TITLE
where i can find this login and password?

### ISSUE THREAD

**Issue by csabavirag** [unitedworldwrestling/arena-public#146]
hello! help me please! how to create account for arena? after install uww arena need to enter login and parol. where i can find this login and password? thank you

_Originally posted by @Artem19qq in https://github.com/unitedworldwrestling/arena-public/issues/107#issuecomment-1786787568_

**Comment by csabavirag** [comment]
If this is a fresh new Arena (with no data) and you can't remember what to use when logging into http://localhost:8080/bracket then the easiest way is to delete the Virtual Machine and import the OVA file again. Thus you can re-start the whole process again.

**Comment by Artem19qq** [comment]
I don't know what to do next???
![unnamed](https://github.com/unitedworldwrestling/arena-public/assets/147393638/c57d13c1-8635-49d4-96f5-c6c72ccf2ba7)

**Comment by csabavirag** [comment]
Open a web browser, visit http://localhost:8080/bracket . You will be redirected to the login form where you can enter the initially given username and password.

Btw, have you watched the webinars from the main page (https://github.com/unitedworldwrestling/arena-public) ? Those give you understanding how the applications work.

**Comment by Artem19qq** [comment]
thanks for the help)

вт, 31 жовт. 2023 р. о 17:44 csabavirag ***@***.***> пише:
