### ISSUE TITLE
Error 502 Bad Gate Way

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#148]
Hello
Dear Mr. csaba
Please guide me to fix the error of running the Arena program. Thanks

![Untitled-1](https://github.com/unitedworldwrestling/arena-public/assets/82810245/929d5fcc-947a-4bbf-b422-1262acfe25fb)

**Comment by csabavirag** [comment]
Hi Mostafa,
this happens when one of the main components is not/cannot be started.
If you are using VM, try to restart it.
If it's on Docker, check in Docker Desktop if the php-fpm-1 container is running.

**Comment by mostafaaghayari** [comment]
Dear Mr.csaba, of course, this error occurred to one of my friends and there is no problem in Docker, but she started it in VM for several times, but it still gives the same error.

**Comment by csabavirag** [comment]
It might require remote troubleshooting. Send me an email pls.

**Comment by euhenpetrov** [comment]
The same
![uww](https://github.com/unitedworldwrestling/arena-public/assets/67595896/7f2b4d2d-aa75-43f2-9fb4-3a0c7426a534)

**Comment by euhenpetrov** [comment]
![0-02-05-a8a32234bce6c1231a3192fc1285c44b72002f6fb947a84a22348b48dbf0fda7_6a0ea2c51f1b8902](https://github.com/unitedworldwrestling/arena-public/assets/67595896/a05681ef-26d4-41bd-9653-6fcf8ead2d89)

**Comment by mostafaaghayari** [comment]
Hello, thank you very much for your help. You solved the problem after updating Windows and re-installing Arena and VM in C drive.
