### ISSUE TITLE
LGTV fall dawn after starting.

### ISSUE THREAD

**Issue by euhenpetrov** [unitedworldwrestling/arena-public#149]
**Which application you are experiencing a problem with**     LGTV Setup 1.2.7.9.3
[eg. Arena, Scoreboard, LGTV, etc]

**Describe the bug**                          

**To Reproduce**
1. Go to '...'  settings of LGTV (put on all nessesary setting: correct ip scoreboard).
2. Click on '....'       start LGTV
4. See error       lgtv  does not start (green screen shuts dawn).

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome, edge]

**Additional context** I  tryed LGTV with different laptops and had the same situation.

**Comment by ybouaziz** [comment]
Hello @euhenpetrov ,

Can you please send me the trace.log file of your LGTV.

Thanks!

**Comment by euhenpetrov** [comment]
Hi. If it is not the info that you want please let me know.

пт, 5 янв. 2024 г. в 03:41, Youssef Bouaziz ***@***.***>:

**Comment by Strassbauer** [comment]
I have the same problem with LGTV  1.2.7.9.6. 

I do the settings and start the LGTV a green windows appears. 
When I start the Timing the LGTV shut down.

**Comment by ybouaziz** [comment]
Hello @Strassbauer 

Can you share your United World Wrestling - LGTV Responsive.exe.Config file.

Best regards,

**Comment by Strassbauer** [comment]
> Hello @Strassbauer
> 
> Can you share your United World Wrestling - LGTV Responsive.exe.Config file.
> 
> Best regards,

Hello  Mr. Bouaziz

I was able to solve the problem. 
The problem was that the user did not have write access to the programme folder. 

Can you tell me what the correct settings are for the following scenario? 

Streaming via OBS on Youtube. 

Camera image via capture card to the streaming PC

**Comment by alexander-pakhomov** [comment]
I noticed that for lgtv to work, obs must be turned on, otherwise it will crash xd

**Comment by ybouaziz** [comment]
Hello, here is the new version of LGTV, it fix the installer and include new feature NDI
https://we.tl/t-npTeXsW4KQ

**Comment by euhenpetrov** [comment]
Awesome, thanks!

нд, 12 трав. 2024 р., 17:41 користувач Youssef Bouaziz <
***@***.***> пише:

**Comment by DmitryPWL** [comment]
Hello all,
Also keep getting this problem, on some laptops LGTV starts ok, but on others doesn't although they may not differ in terms of hard/software. The problem won't go away with the newer versions of LGTV.
I attach a few logs when it failed to work.

[trace1.log](https://github.com/user-attachments/files/19096877/trace1.log)
[trace2.log](https://github.com/user-attachments/files/19096876/trace2.log)

**Comment by csabavirag** [comment]
@DmitryPWL Can you open up Windows Explorer and navigate to `%LOCALAPPDATA%\United_World_Wrestling` folder. Then delete/rename the folder inside and launch LGTV again.
Does that fix your startup issue?

**Comment by csabavirag** [comment]
Does "fall" mean LGTV crashes and you must restart the app? If so, please run Event Viewer and search for the crash log. It must be under Windows Logs => Application. We need the detail of the crash log for further analysis.

**Comment by DmitryPWL** [comment]
> Does "fall" mean LGTV crashes and you must restart the app? If so, please run Event Viewer and search for the crash log. It must be under Windows Logs => Application. We need the detail of the crash log for further analysis.

Exactly. More specificaly, as soon as I start the timer for a new match on UWWTiming the count is not transferred to the graphics, the cursor turns a frozen round and in a few secs LGTV crashes.
I attach the logs you requested, hopefully this clears things up.

[Windows Logs.zip](https://github.com/user-attachments/files/19217771/Windows.Logs.zip)

**Comment by csabavirag** [comment]
Can you go to LGTV settings -> Branding and at the bottom, there is the "Event title". Please change that to something like "Test" (at least 2 characters).
And see if you experience the crash again.

**Comment by DmitryPWL** [comment]
> Can you go to LGTV settings -> Branding and at the bottom, there is the "Event title". Please change that to something like "Test" (at least 2 characters). And see if you experience the crash again.

Yes, that finally solved the issue. I also had to tick the checkbox, otherwise the renaming wouldn't work. Thank you for your assistance!

**Comment by csabavirag** [comment]
Thanks for confirming! we will work on a fix to avoid this without changing the Event title value.
