### ISSUE TITLE
IMPORT ISSUE

### ISSUE THREAD

**Issue by lucha1234** [unitedworldwrestling/arena-public#151]
**Which application you are experiencing a problem with**
Arena

**Describe the bug**
The import stops at 52 percent and I cannot continue the import. I tried updating my computer and removing the program and it doesn't work.

**Screenshots**
<img width="1095" alt="Captura de pantalla 2023-12-08 a la(s) 11 29 07 p m" src="https://github.com/unitedworldwrestling/arena-public/assets/153345739/70f62b6d-d14d-45e3-957e-2a9cba6ce76b">

**Desktop (please complete the following information):**
Safari and Chrome

**Comment by csabavirag** [comment]
If it's reproducible, please share your import XLS/ODF file.
Or you can share the logs from http://localhost:8080/jobs . Open the import job and share the details of that job.

**Comment by Strassbauer** [comment]
I wanted to try the import with the Example file. 

the import did´nt start. 

08:42:48 CRITICAL  [console] Error thrown while running command "--env=prod --verbose arena:import:athletes --jms-job-id=10 1eebf4b7-a17d-6dc2-9fc2-3bb0af928e93 --file='/var/www/arena/phpshared/140730733465b8b685896c96.73586102.xlsx' --skip-first". Message: "invalid_grant" ["exception" => League\OAuth2\Client\Provider\Exception\IdentityProviderException { …},"command" => "--env=prod --verbose arena:import:athletes --jms-job-id=10 1eebf4b7-a17d-6dc2-9fc2-3bb0af928e93 --file='/var/www/arena/phpshared/140730733465b8b685896c96.73586102.xlsx' --skip-first","message" => "invalid_grant"]

In Arena.php line 198:
                                                                       
  [League\OAuth2\Client\Provider\Exception\IdentityProviderException]  
  invalid_grant                                                        
                                                                       

Exception trace:
  at /var/www/arena/current/vendor/unitedworldwrestling/oauth2-arena/src/Provider/Arena.php:198
 Unitedworldwrestling\OAuth2\Client\Provider\Arena->checkResponse() at /var/www/arena/current/vendor/league/oauth2-client/src/Provider/AbstractProvider.php:628
 League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse() at /var/www/arena/current/vendor/league/oauth2-client/src/Provider/AbstractProvider.php:537
 League\OAuth2\Client\Provider\AbstractProvider->getAccessToken() at /var/www/arena/current/src/RestClient/Client.php:110
 App\RestClient\Client->request() at /var/www/arena/current/src/RestClient/Client.php:144
 App\RestClient\Client->request() at /var/www/arena/current/src/Arena/ApiBundle/Utility/Controller.php:70
 App\Arena\ApiBundle\Utility\ConfigManager->getWeightCategories() at /var/www/arena/current/src/Command/ArenaImportAthletesCommand.php:104
 App\Command\ArenaImportAthletesCommand->execute() at /var/www/arena/current/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /var/www/arena/current/vendor/symfony/console/Application.php:1058
 Symfony\Component\Console\Application->doRunCommand() at /var/www/arena/current/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/arena/current/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /var/www/arena/current/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/arena/current/vendor/zolex/job-queue-bundle/JMS/JobQueueBundle/Console/Application.php:47
 JMS\JobQueueBundle\Console\Application->doRun() at /var/www/arena/current/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /var/www/arena/current/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:54
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at /var/www/arena/current/vendor/autoload_runtime.php:35
 require_once() at /var/www/arena/current/bin/console:12

arena:import:athletes [--file FILE] [--skip-first] [--] <event_id>

[ Retry Job](http://192.168.8.7:8080/jobs/10/retry)
Click on the next button to create a new job to retry this failed one.

**Comment by csabavirag** [comment]
Could you please upgrade to the latest version and try again?

**Comment by Strassbauer** [comment]
thank you it works now.
