### ISSUE TITLE
Uww timing

### ISSUE THREAD

**Issue by Adamzaki1** [unitedworldwrestling/arena-public#154]
How to add logos to the uww timing app so the logos can appear to the people on the scoreboard

**Your question**

**Comment by alexkha73** [comment]
Add the logo file to the folder uwwtiming\Images\Flags. The file must be in the format  SVG.

**Comment by ybouaziz** [comment]
Hello Adamzaki, you can add any flag (svg format) to C:\Program Files (x86)\UWWtiming\Images\Flags
The filename should be the same as the team abreviation (ex. Team Name Abr. : EST, Flag File Name: est.svg)

**Comment by Adamzaki1** [comment]
Thank you so much Mr. Youssef

احصل على Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
