### ISSUE TITLE
Fight is cheked, in bracket winner is green color but last one doesn't appear in new round of bracket, therefore I can't download bouts to the scoreboard that are underneath of fitght with one wrestler.

### ISSUE THREAD

**Issue by euhenpetrov** [unitedworldwrestling/arena-public#155]
**Which application you are experiencing a problem with**
[eg. Arena, Scoreboard, LGTV, etc]
arena 1.5.92
![Screenshot_3](https://github.com/unitedworldwrestling/arena-public/assets/67595896/14d54dd3-4717-4ab7-a5cc-92ed042fd352)
![Screenshot_4](https://github.com/unitedworldwrestling/arena-public/assets/67595896/793457cc-389b-4587-89bd-ada502a37062)
![Screenshot_5](https://github.com/unitedworldwrestling/arena-public/assets/67595896/97066eeb-df25-4744-bb26-d80209ef2407)
So we can see that bout #9 was cheked but bout #23 has not been formed.
![Screenshot_6](https://github.com/unitedworldwrestling/arena-public/assets/67595896/518dd347-1a54-4bd3-b17e-c43bd4c53dad)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome, edge]

**Additional context**

**Comment by csabavirag** [comment]
What happens if you re-save match # 9?

**Comment by euhenpetrov** [comment]
when I canceled the results of the battle and entered them manually, an error occurred like oops..... In order to continue the competition, I had to urgently cancel all matches in the weight category and re-create them. Then manually enter the previous results.

**Comment by csabavirag** [comment]
If you are finished with the event, please contact me and I'd like to collect logs from your Arena.

**Comment by euhenpetrov** [comment]
I finished yesterday.

пн, 29 січ. 2024 р., 14:38 користувач csabavirag ***@***.***>
пише:
