### ISSUE TITLE
Error 500-  internal server

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#156]
Hello, dear Mr.Csaba
Please guide me to fix the " 500 -  internal server error  "that occurred after updating version 1.5.92 Thanks. 

![Untitled-2](https://github.com/unitedworldwrestling/arena-public/assets/82810245/e24dcdd3-c298-4ce4-b53c-c618ddacfb3f)

**Comment by csabavirag** [comment]
It looks like you had network outage during the upgrade. Do you still get error when trying to access Arena?

**Comment by euhenpetrov** [comment]
This may be a common problem. It happened to me many times. I had to delete and reinstall the arena. It would be nice if there was some guidance on how to fix this problem yourself.

**Comment by csabavirag** [comment]
To troubleshoot these cases, either need remote support access to your Arena or have a VM export uploaded somewhere and share the link to the ova file privately. @mostafaaghayari which option would you prefer?

**Comment by mostafaaghayari** [comment]
Hello, Mr. Csaba
The problem was solved by uninstalling and reinstalling. Thank
