### ISSUE TITLE
LGTV wrong file on installation

### ISSUE THREAD

**Issue by gkaravitis** [unitedworldwrestling/arena-public#159]
**Which application you are experiencing a problem with**
LGTV

**Describe the bug**
When trying installing the LGTV application in the downloading section a file hash mismatch is happening and the installation is not continuing.

**To Reproduce**
Just trying and download and install the latest version of LGTV.

**Comment by Valdyrnho** [comment]
> **Which application you are experiencing a problem with** LGTV
> 
> **Describe the bug** When trying installing the LGTV application in the downloading section a file hash mismatch is happening and the installation is not continuing.
> 
> **To Reproduce** Just trying and download and install the latest version of LGTV.

C'est la dernière version que j'ai installé et qui ne donne pas. C'est quelle dernière version que je vais encore essayer de télécharger pour installer. Ok dite moi sil vous plait s'il je peux procéder. Merci

**Comment by gkaravitis** [comment]
Any update on this issue we are unable to install the new LGTV version.

**Comment by prosfygas33** [comment]
@csabavirag  same problem here, the last 2-3 weeks, we try to install the latest version of LGTV but file hash mismatch error occured when we trying to install. The old version of LGTV dont work properly.  Any update?

**Comment by csabavirag** [comment]
we are working on a fix. Please give us a few days and a new installer will be released.

**Comment by gkaravitis** [comment]
Hello,
Any updates on this issue we have an upcoming event the following days .
Thanks in advance

**Comment by ybouaziz** [comment]
Hello, here is the new version of LGTV, it fix the installer and include new feature NDI
https://we.tl/t-npTeXsW4KQ
