### ISSUE TITLE
Can I create the name of my competition in LGTV app.?

### ISSUE THREAD

**Issue by euhenpetrov** [unitedworldwrestling/arena-public#16]
When I set up the scoreboard and LGTV in the competition type menu, I can only select the names of the tournaments offered by the program. In Budapest, the name of the tournament was used at the OG qualifying tournament in LGTV. This implies that the option to create your own tournament name exists. How can I enter the name of my tournament in LGTV?

**Comment by bouaziz1991** [comment]
Hello Euhen,

In next release we will take care of customizing graphics colors and event name.

Best regards.

**Comment by bouaziz1991** [comment]
Hello @euhenpetrov 

a new version of LGTV is ready here ;) https://github.com/unitedworldwrestling/arena-public/tree/releases/lgtv

Have a good day!

**Comment by euhenpetrov** [comment]
Thanks a lot!!!

ср, 15 вер. 2021, 16:00 користувач Youssef BOUAZIZ ***@***.***>
пише:

**Comment by ybouaziz** [comment]
Hello @euhenpetrov 

Your issue should be fixed in last version of LGTV.
