### ISSUE TITLE
Broken bracket

### ISSUE THREAD

**Issue by euhenpetrov** [unitedworldwrestling/arena-public#160]
**Which application you are experiencing a problem with** arena 1.5.92.5
[eg. Arena, Scoreboard, LGTV, etc]

**Describe the bug** Some competition brackets was broken and did not describe all competitors during tournament.
![Screenshot_2](https://github.com/unitedworldwrestling/arena-public/assets/67595896/6b278697-0f56-4ef7-8c6b-247d233a0468)
![Screenshot_2](https://github.com/unitedworldwrestling/arena-public/assets/67595896/f21570a7-1509-4bee-8c42-af9201dc69fd)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome, edge]

**Additional context**

**Comment by csabavirag** [comment]
Thanks for reporting. We are looking into it.

**Comment by csabavirag** [comment]
You should get the fix in the upcoming Arena version

**Comment by euhenpetrov** [comment]
Hi Csaba. Could you help me upgrade my master 193.26.209.19 (
https://arena.uw.in.ua). The upgrading process has started but it is
pending and there is no progress. The client had success in updating.
Have a good day! Thanks.

чт, 7 мар. 2024 г. в 21:35, Euhen Petrov ***@***.***>:
