### ISSUE TITLE
Ошибка "502 Bad Gateway" при входа в localhost:8080 

### ISSUE THREAD

**Issue by MoSuMoV** [unitedworldwrestling/arena-public#166]
502 Bad Gateway when i enter to the localhost... Please help me!!! 
![20240512_100923](https://github.com/unitedworldwrestling/arena-public/assets/169576609/e6b4f2cb-730a-443b-9189-a9583cc9e8b5)
![20240512_101017](https://github.com/unitedworldwrestling/arena-public/assets/169576609/0112197d-2a96-41d1-bb5f-8cbc3fb31331)

**Comment by prosfygas33** [comment]
Hello @MoSuMoV , 

Maybe you have a port conflict, this occurs when 2 services are configured to bind to the same port number (in this case 8080) ?

**Comment by MoSuMoV** [comment]
And How can I solve the problem? I restarted Virtual Machine but it doesn't help me... There seems to be no way to solve the problem(((( It is very important for me😢

**Comment by MoSuMoV** [comment]
And by the way, how can I find Scoreboard version 1.26...?  (old version)
@csabavirag 
@prosfygas33

**Comment by csabavirag** [comment]
@MoSuMoV Drop a mail to IT@UWW and we can discuss how to check your Arena remotely.

With regards to Scoreboard 1.26, we only have version 1.2.30.5 and onwards.

**Comment by MoSuMoV** [comment]
@csabavirag Thank you for constantly answering my letters! Should I write a letter again to IT@UWW.org?

**Comment by csabavirag** [comment]
Ahh, sorry, I sent you a mail.

**Comment by MoSuMoV** [comment]
@csabavirag 
![17163898567012988990764249816529](https://github.com/unitedworldwrestling/arena-public/assets/169576609/172671f2-1edd-400b-8664-8421c7a1f62e)
If anything, my computer is in Russian language. But, I know English quite well

**Comment by csabavirag** [comment]
The host computer is running slow with low resources available. That blocks the virtual machine from running smoothly, thus it cannot start all the necessary services for Arena.

I recommend you to try on a computer with more RAM (8GB or more) and CPU (i3/i5 or better) resources.
