### ISSUE TITLE
Whoops, looks like something went wrong. 404 - Not Found

### ISSUE THREAD

**Issue by anvar59** [unitedworldwrestling/arena-public#169]
**Which application you are experiencing a problem with**
[eg. Arena, Scoreboard, LGTV, etc]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome, edge]

**Additional context**

**Comment by csabavirag** [comment]
@anvar59 I'm sorry, but without any details we can't help. Please re-open this issue and be more specific on your problem, answer all the questions in the issue template.
