### ISSUE TITLE
1.5.72 SKORBORD ÇALIŞMIYOR-1.5.72 SCOREBOARD DOES NOT WORK

### ISSUE THREAD

**Issue by dur386** [unitedworldwrestling/arena-public#17]
**Which application you are experiencing a problem with**
[eg. Arena, Scoreboard, LGTV, etc]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome, edge]

**Additional context**

**Comment by dur386** [comment]
Arena 1.5.70 sürümünde SKORBORD programı çalışmıyor.yeni güncellme yapıp SKORBORD aktif hale getirebilir misiniz ?

**Comment by csabavirag** [comment]
Hello @dur386, could you please write in English?

**Comment by dur386** [comment]
SKORBORD program does not work in Arena version 1.5.72. Can you make a new update and activate SCORBORD?

**Comment by dur386** [comment]
@csabavirag Hİ .SKORBORD program does not work in Arena 1.5.72 version. Can you make a new update and activate SCORBORD?

**Comment by csabavirag** [comment]
In which part of the Scoreboard do you see problems?
I double checked it for you and I successfully loaded and completed matches with UWWtiming 1.2.31.1 and Arena 1.5.72.
Please fill out the template above (the opening question) with as many details as you can (including screenshot about the error if possible). That might help us finding the problem quickly.

**Comment by dur386** [comment]
I cannot stream data to the computer that I connected to the table referees and the computer with Arena installed.. The scoreboard works on the old version but 1.5.72 does not work. I cannot connect to UWWtiming 1.2.31.1 and Arena 1.5.72

**Comment by dur386** [comment]
![skorbord sorun](https://user-images.githubusercontent.com/79795576/112891166-78482480-90e0-11eb-88df-20be38be8490.jpg)

**Comment by dur386** [comment]
@csabavirag Good evening ..My problem is I cannot connect from my ARENA installed computer to UWWtiming 1.2.31.1 and Arena 1.5.72 that I installed on the other computer. The problem still persists.

**Comment by csabavirag** [comment]
Hey @dur386 I don't want to disagree with you, but your screenshot is about UWWtiming 1.2.29.27. 
Please send a mail to it@uww.org to escalate your problem.

**Comment by csabavirag** [comment]
I believe the problem was about the wrong UWWtiming version. I found out that the download link at arena.uww.io was referring to an older version of the app. The link is fixed.
After installing the new version, connection is fine and Scoreboard works as expected.
