### ISSUE TITLE
Onvenue's new function to display 4 live statistics of an event

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#170]
Dear csaba
Unfortunately, the said statistics were not displayed for me in version 1.5.95  Please guide me on how to use (Onvenue's new function to display 4 live statistics of an event)

**Comment by csabavirag** [comment]
If you visit Onvenue portal for an event (either a running event or a finished one) and open this options

> ![image](https://github.com/unitedworldwrestling/arena-public/assets/10976654/04b98588-d421-42c5-8ef8-c0285f55ea5f)

in a few seconds you should receive something similar

> ![image](https://github.com/unitedworldwrestling/arena-public/assets/10976654/6ef7f87f-3979-44c8-936d-52a4a7de55f9)

Please note, this page uses external libraries for the charts, so you must have Internet connectivity at least for the time while the page loads. Then the data is refreshed in the background every minute (without a full page reload), so you can disconnect your local network from Internet once the first graphs are displayed.

**Comment by mostafaaghayari** [comment]
Unfortunately, after about 10 minutes, the graphs were not displayed again.

https://github.com/unitedworldwrestling/arena-public/assets/82810245/64450122-e2a5-42b7-95a2-5c1bac328a75

**Comment by csabavirag** [comment]
can you drop a mail to IT@uww?

**Comment by mostafaaghayari** [comment]
I sent to your email address

**Comment by mostafaaghayari** [comment]
The address of Anydesk was e-mailed.

**Comment by mostafaaghayari** [comment]
Mr. csaba, thank you very much for your guidance and help.

**Comment by csabavirag** [comment]
It looked like you had 2 things missing from the VirtualBox image. It should be fixed in the next Arena version.
