### ISSUE TITLE
Repechages are not held

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#171]
dear csaba
In some competitions, the considered repechages may not be held according to the competition process and these repechages will still remain in the competition program, even the repechages that were not held on the first day of the competition will still be displayed above the programs of the second day. Please check and advise.

![1234](https://github.com/unitedworldwrestling/arena-public/assets/82810245/7b2b59e3-8831-4dd6-81e1-4ad052bad77d)

**Comment by csabavirag** [comment]
We removed canceled matches from the Start list in Arena version 1.5.96
