### ISSUE TITLE
Error in displaying athletes' names on the scoresheet 

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#172]
Dear CSABA, As you can see in the picture, the blue and red names at the top and bottom of the result sheet are not the same and have been reversed ,please check. thanks

![Untitled](https://github.com/unitedworldwrestling/arena-public/assets/82810245/19897a72-a8e5-4880-b090-743d7041e86c)

![Untitled1](https://github.com/unitedworldwrestling/arena-public/assets/82810245/751344c1-1ae3-471e-80d8-91c9ba2c1267)

![Untitled3](https://github.com/unitedworldwrestling/arena-public/assets/82810245/7f8ffc8c-f0e1-4458-a18b-55ec6471a324)
![Untitled4](https://github.com/unitedworldwrestling/arena-public/assets/82810245/bc4e085d-c776-4866-aab6-2a8adfc2cc7d)

[Uploading dbdump.sql.zip…]()

**Comment by csabavirag** [comment]
Thanks for notifying us. We also notices in some cases the fighters are shown in wrong order on the match details page.
The fix is on the way...

**Comment by mostafaaghayari** [comment]
Thanks.
