### ISSUE TITLE
I can't add atheletes to the event using Add a athlete endpoint. How to add weight category?

### ISSUE THREAD

**Issue by antohasv** [unitedworldwrestling/arena-public#174]
**Which application you are experiencing a problem with**
Arena

**Describe the bug**
I use API endpoints:
https://arena.sportrec.online/api/doc/

**To Reproduce**
1. Go to and run  Post /api/json/athlete/{sportEventId}

**Expected behavior**
The athlete doesn't add to the event

**Comment by csabavirag** [comment]
Have you tried to use the collection + environment import into Postman and create the desired API call from the examples?
https://github.com/unitedworldwrestling/arena-public/tree/master/Resources/Postman

**Comment by antohasv** [comment]
Hey @csabavirag 

Thank you for your quick reply! Here is a quick video:
https://www.loom.com/share/65b96d67a8314a12aeb98cd383f0be47



I still have the issue to add  Athletes using API.

**Comment by csabavirag** [comment]
You stopped at 2.i from my other comment at https://github.com/unitedworldwrestling/arena-public/issues/175#issuecomment-2178598797

You just created an athlete, but it's not associated with any weight category. It's important to call 2.ii (create fighter), where you can do this association.

As you can see, the `Location` header attribute of the Create Athlete (POST /api/json/athlete/{{sportEventId}}) contains the athleteID of the newly created athlete. This athleteID must be passed to the Create Fighter (POST /api/json/fighter/{{athleteID}}) endpoint to assign a weight category to this athlete.

<img width="982" alt="image" src="https://github.com/unitedworldwrestling/arena-public/assets/10976654/b5290467-1a35-4dac-a21e-a1c5be5c750f">

**Comment by antohasv** [comment]
@csabavirag 
thanks
