### ISSUE TITLE
How Webhooks work in API?

### ISSUE THREAD

**Issue by antohasv** [unitedworldwrestling/arena-public#176]
**Which application you are experiencing a problem with**
Arena

**Describe the bug**
I'm looking to get real-time updates from Arena by API: 
– when event, result is changing

It seems that Webhook is what I need but there are no any docs how to use it.

**Comment by csabavirag** [comment]
Would you require further details than in https://github.com/unitedworldwrestling/arena-public/issues/138#issuecomment-1658402127?
