### ISSUE TITLE
API: 500 error when trying to create a new event using API

### ISSUE THREAD

**Issue by antohasv** [unitedworldwrestling/arena-public#177]
**Which application you are experiencing a problem with**
Arena

**Describe the bug**
500 error when trying to create a new event using API
POST https://arena.sportrec.online/api/json/sport-event/

Body:
{
  "country": "AT",
  "timezone": "Europe/Volgograd",
  "name": "laborum",
  "startDate": "2024-06-26T05:54:58.228Z",
  "endDate": "2024-06-10T17:00:15.485Z",
  "rankingType": "individual",
  "tournamentType": "singlebracket",
  "sessionType": "1day",
  "eventType": "continental-championships",
  "continent": "world",
}

**Comment by csabavirag** [comment]
You had a typo in the JSON (Body). Remove the trailing `,` after the `continent` attribute to fix the JSON syntax.
However it's not going to be enough, there are a few mandatory attributes you also have to provide at least.
Also, even if `addressLocality` is not mandatory, I would recommend you to set that as well.

```json
{
"country": "AT",
"timezone": "Europe/Volgograd",
"name": "laborum",
"startDate": "2024-06-26T05:54:58.228Z",
"endDate": "2024-06-10T17:00:15.485Z",
"rankingType": "individual",
"tournamentType": "singlebracket",
"sessionType": "1day",
"eventType": "continental-championships",
"continent": "world",

"countdown": 1,
"copyScoresheet": 2,
"matAssignment": 1,
"secure": 0,

"addressLocality": "Host city"
}
```

**Comment by antohasv** [comment]
@csabavirag thanks
