### ISSUE TITLE
Bug in Arena: 500 - Internal Server Error

### ISSUE THREAD

**Issue by Petro-wr** [unitedworldwrestling/arena-public#18]
Match #91 gas last in event today. User of UWWtiming ended this match after it finish. But in Arena interface match #91 is not availiable to check. Red button (#91) in quick action bar not aktiv. Restart of Arena was not help in this problem.

Additional information:
Arena version: (Remote: )
Branch:
Error URL: http://localhost:8080/bracket/fight/show/b4065b41-8f9b-11eb-a377-080027263834

![500](https://user-images.githubusercontent.com/81524657/112759593-5c6b5280-8ffc-11eb-8796-e8201db6cb44.jpg)

**Comment by csabavirag** [comment]
Please send a mail to it@uww.org. We will contact you directly because in your case it's require remote troubleshooting.

**Comment by Petro-wr** [comment]
Thank you! ok.

**Comment by csabavirag** [comment]
It seems the error was caused by the wrong import sheet format. Don't forget, the first column is for the team names! :)

**Comment by Petro-wr** [comment]
Thank you!
I will be more attentive.

пн, 29 бер. 2021 о 17:47 csabavirag ***@***.***> пише:
