### ISSUE TITLE
U11-U13 WEIGHT ADAPTATION

### ISSUE THREAD

**Issue by dkaya60** [unitedworldwrestling/arena-public#181]
Have a nice day . There are no weights determined for the competitions held in our country(Türkiye) in the u11-u13 categories. (30-34-38-41-44-48-52-57-62-68-78-88) How can we adapt these weights in the arena?

![Ekran Görüntüsü (50)](https://github.com/unitedworldwrestling/arena-public/assets/79795576/cd837cb4-ac53-4401-8395-2c0e656f2657)

![Ekran Görüntüsü (51)](https://github.com/unitedworldwrestling/arena-public/assets/79795576/044fa669-73bf-48d2-b28a-d207ed58b256)

**In which application you miss a feature**
[eg. Arena, Scoreboard, LGTV, etc]

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by csabavirag** [comment]
Here you can find a short video on how to add new weight categories with Visual Editor under Sports Config menu.
I hope this helps.

https://github.com/unitedworldwrestling/arena-public/assets/10976654/97142090-1d4d-476e-8fb7-7c8c9cc53332

**Comment by dkaya60** [comment]
Thank you very much Csabavirag, I got my job done. It was very useful. Thank you :)
