### ISSUE TITLE
UWW timing app doesnt open

### ISSUE THREAD

**Issue by palvespt** [unitedworldwrestling/arena-public#182]
Dear Csaba,

Can you help on this?

We have the uww timing installed on the competitions computers however on the last competition the uww software on PC1 stop working and since then its not opening it.

I´ve tried witout the anti-virus, with the virus (just like before) but doent open any of the UI,.

Olny message that i have (which should not be a problem) is that the ip address is different ans ask me to change. However because doesnt open the UI im unable to change or re-configure it.

Finnaly i also compared the settings with the others pc´s and everything is he same.
[screen-capture.webm](https://github.com/unitedworldwrestling/arena-public/assets/94856801/8dfbb48c-ad2a-4760-b78f-cb259218ba72)

Please check the video attached.

How can i fix this.

Thanks in advance for your support

Pedro Alves

**Comment by palvespt** [comment]
Dear Csaba,

Im sorry, i´ve should troubleshooting on the issues tab before posting.

I was able to fix it with this solution:

https://github.com/unitedworldwrestling/arena-public/issues/119#issuecomment-1495923590 

Now the UI open and i can use it / change the ip adress etc...

The name of the folder was: UWWtiming.exe_Url_ftcgviwkzcbns2glbkqoaghpywspi5by  

Any reason by this happens? Can we prevent it?

Thanks in advance for your support

**Comment by csabavirag** [comment]
Pedro, in Windows Explorer please navigate to `%LOCALAPPDATA%\UnitedWorldWrestling\logs` folder (this is a short version of "C:\Users\<username\AppData\Local\UnitedWorldWrestling\logs" folder). Here you may find several log files, we are interested about the most recent one (with the current day in the filename).
This file may give us indication on the crash so it's important to us to have this file.

Once you made a copy of the logfile and shared with us, you can try with a quick workaround. 
If you remove all the configuration settings of UWWTiming app (to get the app in the same state as right after a fresh install) that can help if the crash is related to the application itself.
You can delete all the folders started with "UWWtiming.exe_" and then a long text in the folder name from `%LOCALAPPDATA%\UnitedWorldWrestling` folder. These folders hold some settings across different versions and if you delete them, Scoreboard will recreate the config at the next start.

**Comment by palvespt** [comment]
Hi Csaba,
Sry the late reply.

Attached you will find the log from the competition (06) and the log from yesterday (09).
Thanks again for your support.

[2024-07-06.log](https://github.com/user-attachments/files/16159955/2024-07-06.log)
[2024-07-09.log](https://github.com/user-attachments/files/16159956/2024-07-09.log)

**Comment by csabavirag** [comment]
Thanks Pedro for the logs.
Did you try to delete the "UWWtiming.exe_*" folders from `%LOCALAPPDATA%\UnitedWorldWrestling` folder? Your logs from yesterday are collected after the deletion of those folders?

**Comment by palvespt** [comment]
My log from yesterday was after rename the folder to : UWWtiming.exe_

For some reason the folder name was UWWtiming.exe_Url_ftcgviwkzcbns2glbkqoaghpywspi5by
