### ISSUE TITLE
how to check matches?......

### ISSUE THREAD

**Issue by MoSuMoV** [unitedworldwrestling/arena-public#183]
**Which application you are experiencing a problem with**
-- ARENA

**Describe the bug**
I can't tap on the "SAVE" button., because there is a button of "SETTINGS". How can I continue my event?  I want to move to a new stage of meetings and create new matches. Please help)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser -- chrome
 Arena version 1.5.93
screenshots^
![Снимок экрана 2024-07-18 105622](https://github.com/user-attachments/assets/ecfe1b66-bf55-4167-99de-49891736e766)
![Снимок экрана 2024-07-18 111236](https://github.com/user-attachments/assets/4494a070-a1cd-46e9-b449-da2b0cab3f26)

**Comment by mostafaaghayari** [comment]
Hello, please reduce the screen size

https://github.com/user-attachments/assets/d802777f-ccd7-4323-b17f-311cf6bbd43e

**Comment by MoSuMoV** [comment]
> Здравствуйте, пожалуйста, уменьшите размер экрана.
> 
>  Видео_2024-07-18_230448.mp4

Dear friend, Thank you very much!!! I thought it was a big problem, turns out it's so simple!
