### ISSUE TITLE
Bracket print error

### ISSUE THREAD

**Issue by euhenpetrov** [unitedworldwrestling/arena-public#184]
**Which application you are experiencing a problem with**
[eg. Arena, Scoreboard, LGTV, etc]                      arena 1.5.96.1

**Describe the bug**    https://arena.uw.in.ua/uk/weight-category/show/1ef78e91-0b86-666e-aaf2-e37b542678e4/round-robin-results/print
![Screenshot_3](https://github.com/user-attachments/assets/5fcbf263-87f1-4479-a75a-9b1f1e5364e0)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome, edge]

**Additional context**

**Comment by csabavirag** [comment]
The link you provided to GR100kg on your Arena server shows the correct bracket. Did you make a change on your Arena, or there was something else like an incomplete synchronization?

**Comment by csabavirag** [comment]
Please re-open the issue if you have further details. Thanks!
