### ISSUE TITLE
LGTV is closing

### ISSUE THREAD

**Issue by wellyngson** [unitedworldwrestling/arena-public#186]
**Which application you are experiencing a problem with**
LGTV

**Describe the bug**
When I start the LGTV and start the figth in UWW timing the LGTV close

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome, edge]

**Additional context**

**Comment by csabavirag** [comment]
I believe this is a duplicate of #185
