### ISSUE TITLE
Why is it not online in the new arena update with Scoboard?

### ISSUE THREAD

**Issue by behzadbadr** [unitedworldwrestling/arena-public#188]
**Which application you are experiencing a problem with**
[eg. Arena, Scoreboard, LGTV, etc]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome, edge]

**Additional context**

**Comment by csabavirag** [comment]
Please re-open this issue with more details! Fill out all the sections in the bug template with relevant info to provide clear description of your question/concern.
Thanks!
