### ISSUE TITLE
Upgrading from 1.5.70.1 to 1.5.72 fails

### ISSUE THREAD

**Issue by kirodeniro** [unitedworldwrestling/arena-public#19]
**Which application you are experiencing a problem with**
[Arena]

**Describe the bug**
Upgrading fails

**To Reproduce**
1. Go to 'Home'
2. Click on 'Upgrade to 1.5.72'

**Expected behavior**
receive new version

**Screenshots**
Upgrading...
Fetching origin
Segmentation fault (core dumped)
Maintenance mode: on
Upgrading to version 1.5.72
Latest version already installed. Done.
Successfully installed bundler-2.1.4
Parsing documentation for bundler-2.1.4
Done installing documentation for bundler after 6 seconds
1 gem installed
Following files may not be writable, so sudo is needed:
  /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/environment
Using rake 13.0.3
Using net-ssh 6.1.0
Using net-scp 3.0.0
Using sshkit 1.21.1
Using airbrussh 1.4.0
Using bundler 2.1.4
Using concurrent-ruby 1.1.7
Using i18n 1.8.7
Using capistrano 3.15.0
Using capistrano-composer 0.0.6
Using capistrano-file-permissions 1.0.0
Using capistrano-npm 1.0.3
Using capistrano-nvm 0.0.7
Using capistrano-symfony 2.0.0 from https://github.com/unitedworldwrestling/capistrano-symfony.git (at patch_122@0182ad8)
Bundle complete! 4 Gemfile dependencies, 14 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Following files may not be writable, so sudo is needed:
  /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/environment
00:00 nvm:wrapper
      01 mkdir -p /tmp/arena/
    ✔ 01 vagrant@127.0.0.1 2.322s
      Uploading /tmp/arena/nvm-exec.sh 100.0%
      02 chmod +x /tmp/arena/nvm-exec.sh
    ✔ 02 vagrant@127.0.0.1 2.131s
00:07 git:wrapper
      01 mkdir -p /tmp
    ✔ 01 vagrant@127.0.0.1 1.028s
      Uploading /tmp/git-ssh-6b32aa9a1b74de1814a9.sh 100.0%
      02 chmod 700 /tmp/git-ssh-6b32aa9a1b74de1814a9.sh
    ✔ 02 vagrant@127.0.0.1 0.868s
00:10 git:check
      01 git ls-remote git@github.com:unitedworldwrestling/arena.git HEAD
      01 928f88066b83df560883aa842f675e31e771dd71	HEAD
    ✔ 01 vagrant@127.0.0.1 2.918s
00:12 deploy:check:directories
      01 mkdir -p /var/www/arena/shared /var/www/arena/releases
    ✔ 01 vagrant@127.0.0.1 0.888s
00:13 deploy:check:linked_dirs
      01 mkdir -p /var/www/arena/shared/var/log /var/www/arena/shared/public/uploads
    ✔ 01 vagrant@127.0.0.1 0.788s
00:14 deploy:check:make_linked_dirs
      01 mkdir -p /var/www/arena/shared
    ✔ 01 vagrant@127.0.0.1 0.980s
00:16 deploy:create_local_env_file
      01 touch .env.local
    ✔ 01 vagrant@127.0.0.1 0.966s
00:24 git:clone
      The repository mirror is at /var/www/arena/repo
00:25 git:update
      01 git remote set-url origin git@github.com:unitedworldwrestling/arena.git
    ✔ 01 vagrant@127.0.0.1 1.055s
      02 git remote update --prune
      02 Fetching origin
    ✔ 02 vagrant@127.0.0.1 2.503s
00:30 git:create_release
      01 mkdir -p /var/www/arena/releases/20210329120520
    ✔ 01 vagrant@127.0.0.1 1.064s
      02 git archive master | /usr/bin/env tar -x -f - -C /var/www/arena/releases/20210329120520
      02 bash: line 1: 47706 Broken pipe             /usr/bin/env git archive master
      02      47707 Segmentation fault      (core dumped) | /usr/bin/env tar -x -f - -C /var/www/arena/releases/20210329120520
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as vagrant@127.0.0.1: git exit status: 139
git stdout: Nothing written
git stderr: bash: line 1: 47706 Broken pipe             /usr/bin/env git archive master
     47707 Segmentation fault      (core dumped) | /usr/bin/env tar -x -f - -C /var/www/arena/releases/20210329120520

Caused by:
SSHKit::Command::Failed: git exit status: 139
git stdout: Nothing written
git stderr: bash: line 1: 47706 Broken pipe             /usr/bin/env git archive master
     47707 Segmentation fault      (core dumped) | /usr/bin/env tar -x -f - -C /var/www/arena/releases/20210329120520

Tasks: TOP => git:create_release
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as vagrant@127.0.0.1: git exit status: 139
git stdout: Nothing written
git stderr: bash: line 1: 47706 Broken pipe             /usr/bin/env git archive master
     47707 Segmentation fault      (core dumped) | /usr/bin/env tar -x -f - -C /var/www/arena/releases/20210329120520

** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:

 DEBUG [08c7572c] Running if test ! -d /var/www/arena/repo; then echo "Directory does not exist '/var/www/arena/repo'" 1>&2; false; fi as vagrant@127.0.0.1

 DEBUG [08c7572c] Command: if test ! -d /var/www/arena/repo; then echo "Directory does not exist '/var/www/arena/repo'" 1>&2; false; fi

 DEBUG [08c7572c] Finished in 1.260 seconds with exit status 0 (successful).

  INFO [ab6f689f] Running /usr/bin/env git remote set-url origin git@github.com:unitedworldwrestling/arena.git as vagrant@127.0.0.1

 DEBUG [ab6f689f] Command: cd /var/www/arena/repo && ( export PATH="/home/vagrant/.nvm/versions/node/v8.4.0/bin:$PATH" SYMFONY_ENV="prod" NODE_VERSION="v8.4.0" GIT_ASKPASS="/bin/echo" GIT_SSH="/tmp/git-ssh-6b32aa9a1b74de1814a9.sh" ; /usr/bin/env git remote set-url origin git@github.com:unitedworldwrestling/arena.git )

  INFO [ab6f689f] Finished in 1.055 seconds with exit status 0 (successful).

  INFO [99ab2dd7] Running /usr/bin/env git remote update --prune as vagrant@127.0.0.1

 DEBUG [99ab2dd7] Command: cd /var/www/arena/repo && ( export PATH="/home/vagrant/.nvm/versions/node/v8.4.0/bin:$PATH" SYMFONY_ENV="prod" NODE_VERSION="v8.4.0" GIT_ASKPASS="/bin/echo" GIT_SSH="/tmp/git-ssh-6b32aa9a1b74de1814a9.sh" ; /usr/bin/env git remote update --prune )

 DEBUG [99ab2dd7] 	Fetching origin

  INFO [99ab2dd7] Finished in 2.503 seconds with exit status 0 (successful).

 DEBUG [7e8cc8fb] Running if test ! -d /var/www/arena/repo; then echo "Directory does not exist '/var/www/arena/repo'" 1>&2; false; fi as vagrant@127.0.0.1

 DEBUG [7e8cc8fb] Command: if test ! -d /var/www/arena/repo; then echo "Directory does not exist '/var/www/arena/repo'" 1>&2; false; fi

 DEBUG [7e8cc8fb] Finished in 1.243 seconds with exit status 0 (successful).

  INFO [f6eb8d66] Running /usr/bin/env mkdir -p /var/www/arena/releases/20210329120520 as vagrant@127.0.0.1

 DEBUG [f6eb8d66] Command: cd /var/www/arena/repo && ( export PATH="/home/vagrant/.nvm/versions/node/v8.4.0/bin:$PATH" SYMFONY_ENV="prod" NODE_VERSION="v8.4.0" GIT_ASKPASS="/bin/echo" GIT_SSH="/tmp/git-ssh-6b32aa9a1b74de1814a9.sh" ; /usr/bin/env mkdir -p /var/www/arena/releases/20210329120520 )

  INFO [f6eb8d66] Finished in 1.064 seconds with exit status 0 (successful).

  INFO [573e370b] Running /usr/bin/env git archive master | /usr/bin/env tar -x -f - -C /var/www/arena/releases/20210329120520 as vagrant@127.0.0.1

 DEBUG [573e370b] Command: cd /var/www/arena/repo && ( export PATH="/home/vagrant/.nvm/versions/node/v8.4.0/bin:$PATH" SYMFONY_ENV="prod" NODE_VERSION="v8.4.0" GIT_ASKPASS="/bin/echo" GIT_SSH="/tmp/git-ssh-6b32aa9a1b74de1814a9.sh" ; /usr/bin/env git archive master | /usr/bin/env tar -x -f - -C /var/www/arena/releases/20210329120520 )

 DEBUG [573e370b] 	bash: line 1: 47706 Broken pipe             /usr/bin/env git archive master

     47707 Segmentation fault      (core dumped) | /usr/bin/env tar -x -f - -C /var/www/arena/releases/20210329120520

Maintenance mode: off

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [e.g. 89.0.4389.90]

**Comment by csabavirag** [comment]
Was this a one-time issue, or does not matter how many times you run the upgrade, you always get this error?
I could imagine an interim network outage, which caused the network communication broken to Github server.

If the issue persist, we need to connect to your computer remotely.

**Comment by kirodeniro** [comment]
> Was this a one-time issue, or does not matter how many times you run the upgrade, you always get this error?
> I could imagine an interim network outage, which caused the network communication broken to Github server.
> 
> If the issue persist, we need to connect to your computer remotely.

No, this is not a one-time issue, I've tried 7 times with the same error. Even on a different computer. Same issue.

**Comment by csabavirag** [comment]
Could you drop a mail (it@uww.org) and we will send you the instructions for a remote assistance.

**Comment by kirodeniro** [comment]
After several tries (more than 20), I finally managed to update to 1.5.72. I really don't know how it happened. The output shows some errors in the end - on migrations and SQL statements, but now Arena is working and shows version 1.5.72
I'm attaching a log file - may be useful to you.
[update-log.txt](https://github.com/unitedworldwrestling/arena-public/files/6230083/update-log.txt)

**Comment by csabavirag** [comment]
@kirodeniro Thanks Kiril for the log. Those errors are necessary to fix. Do you mind contacting us on the mail above, so a fix could be applied on your Arena.
