### ISSUE TITLE
The title of the pages

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#193]
Hello, Mr. csaba
If it is possible, please include the title of the first page of the athlete list at the beginning of subsequent pages as well.

https://github.com/user-attachments/assets/05c1e5ae-445e-4ced-b57b-0af9407fea97

**Comment by csabavirag** [comment]
Hi Mostafa, thanks for the note. It's going to be available in the next Arena version.

**Comment by mostafaaghayari** [comment]
thank you very much.
