### ISSUE TITLE
The update is only completing up to 30%, and the Draw Manager menu is not appearing.

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#196]
Hi Mr. Csaba,
We're having a problem with some of our systems. They're only updating up to 30% and then getting stuck. Also, the Draw manager isn't appearing on some systems after the update. Can you please advise us on how to fix this?

[
![30%](https://github.com/user-attachments/assets/56a2f9bd-f02f-40d1-bc95-02f7f3228a27)
![Draw manager1](https://github.com/user-attachments/assets/bcdc077d-22a3-42a4-820e-0426f8ea8038)
![Draw manager11](https://github.com/user-attachments/assets/f878aa9f-a268-4a75-871e-316d9df3c758)
](url)

**Comment by mostafaaghayari** [comment]
[30%.zip](https://github.com/user-attachments/files/17804813/30.zip)
[Uploading Draw manager.zip…]()

**Comment by csabavirag** [comment]
Can you go to localhost:8080/jobs and save the log from the upgrade job?

**Comment by csabavirag** [comment]
Do you use the latest VM? Version [1.5.93 ](https://we.tl/t-bEoEJo9u3A)
If so, send me a mail for a remote support session.

**Comment by mostafaaghayari** [comment]
thank you very much .
