### ISSUE TITLE
Scoreboard 1.2.31.1 problem

### ISSUE THREAD

**Issue by theswix** [unitedworldwrestling/arena-public#24]
**Which application you are experiencing a problem 
Arena 1.5.72.1   Scoreboard 1.2.31.1

**Describe the bug**
Custom flags in lowercase Cyrillic *.png (referring to 3 letters abbreviations of Russian regions, e.g. кра.png or адг.png) were uploaded to Arena in Archive.zip file containing "4x3" and "custom" folders as the manual prescribes. Arena uses these flags normally, but Scoreboard starts with either blank field or UWW logo instead of region flag while getting the region name from Arena in Cyrillic correctly.

**To Reproduce**
1. Upload custom flags (see attachment) to Arena
2. Start Scoreboard
3. Get matches from Arena
4. See blank field instead of regional flag in Scoreboard

**Expected behavior**
Customs flags are properly seen on the scoreboard

**Screenshots**

![IMG_20210406_134208](https://user-images.githubusercontent.com/54967199/113669936-a8925300-96de-11eb-961a-6d5b3aa66846.jpg)
![IMG_20210406_134232](https://user-images.githubusercontent.com/54967199/113669948-aaf4ad00-96de-11eb-9b89-1514c26dfc42.jpg)
[Archive.zip](https://github.com/unitedworldwrestling/arena-public/files/6262645/Archive.zip)

**Additional context**
Screenshots and archive file with flags are attached.

**Comment by csabavirag** [comment]
Thanks for reporting this lack of capability. At the moment UWWtiming application does not support displaying custom flags uploaded to Arena. The flags UWWtiming shows are stored locally as part of the application install and not downloaded from Arena.
There is an enhancement logged for this feature, but no commitment on the availability yet.

Until that, the only way to have those custom flags installed to convert your PNG (image) files to SVG (vector graphics format) and copy them to the Flags folder (usually at C:\Program Files (x86)\UWWtiming\Images\Flags) 
You may have to copy the new flags to this folder after every new version install.

See this screenshot:
![image](https://user-images.githubusercontent.com/10976654/113677638-1712e900-96be-11eb-8680-9621df674fbc.png)

**Comment by theswix** [comment]
@csabavirag thank you very much! Already figured that out :) I think it might be useful for other users to mention about this current situation with flags in wiki...
