### ISSUE TITLE
Enhancement with participants table

### ISSUE THREAD

**Issue by theswix** [unitedworldwrestling/arena-public#25]
**In which application you miss a feature**
Arena
**Is your feature request related to a problem? Please describe.**
In 1.5.72 release really nice feature was implemented - now it is possible to see Team list that contains all the teams (having "before draw" label). It would be quite logical to have the same option ("before draw" label attached) with number of entries by team (Participants table). Right now the printing produces zero participants until the draw has been carried out. Only after the draw it is possible to see the overall picture...

**Describe the solution you'd like**
Being able to have nice and handy one-table overview of numbers of entries by team BEFORE the draw

**Comment by csabavirag** [comment]
Thanks! That makes sense. The enhancement request is added to the queue.

**Comment by csabavirag** [comment]
It's available in the most recent version of Arena. Closing the issue.
