### ISSUE TITLE
LGTV

### ISSUE THREAD

**Issue by ahasver28** [unitedworldwrestling/arena-public#26]
**Which application you are interested about**
[eg. Arena, Scoreboard, LGTV, etc]

**Your question**
Hello!
I have a problem with recordings at OBS Studio GFX - I can't frame it. The graphic is not fully displayed because it extends out of the frame and I cannot fit it into the frame. I need help . Where can I set this up?

Greetings, Milos

**Comment by bouaziz1991** [comment]
Dear Milos,

Thank you for your feedback, can you please make a screenshot of the LGTV display and OBS output, so I can help you more.

Best regards.

**Comment by ahasver28** [comment]
![2021-04-14 jpg](https://user-images.githubusercontent.com/82161103/114767608-23571000-9d68-11eb-8ab8-ec5c21f6b6e2.png)
![2021-04-14 (2) jpg](https://user-images.githubusercontent.com/82161103/114767639-2ce07800-9d68-11eb-8ecd-daaa6fd3776e.png)
Hello!
The first graphic is nicely displayed, and the second is in the part that takes time out of the frame.

Best regards, Miloš

**Comment by bouaziz1991** [comment]
Hello @ahasver28

Make sure your screen resolution is 1920x1080 and the zoom is at 100%.
For Scene and Profile settings on OBS, also make sure it is the default settings not to generate LGTV, if you have changed something manually, you can close OBS and go back to the LGTV settings screen and save the settings. settings, it will open OBS with LGTV default settings.

Have a good day.

**Comment by bouaziz1991** [comment]
Hello @ahasver28 

a new version of LGTV is ready here ;) https://github.com/unitedworldwrestling/arena-public/tree/releases/lgtv

Have a good day!

**Comment by realbadal** [comment]
Hello dear @bouaziz1991 
Can you help me about saving the changes I made in the setting of the new Ver. of LGTV (Ver. No 1.2.5.7.6)

**Comment by ybouaziz** [comment]
Hello @realbadal 

Your issue is fixed in the last version of LGTV.

Have a nice day!

**Comment by ahasver28** [comment]
Hello, it doesn't work. When I open a new fight there are no graphics. If I give a challenge it shows it and after the challenge it shows the graphics of competitor 1 and 2. I can assign points to them but when I hit the start time the time on the graphics does not run on the scoreboard it runs normally and after a few seconds the complete LGTV disappears.
![Posnetek zaslona 2024-07-23 213510](https://github.com/user-attachments/assets/d82fc2e9-b08c-4e20-8335-3510e617eb42)
![Posnetek zaslona 2024-07-23 213546](https://github.com/user-attachments/assets/9e799863-93a5-43a9-aee4-3b64171fc8cb)
![Posnetek zaslona 2024-07-23 213614](https://github.com/user-attachments/assets/d6f23239-68ec-4f9d-8d49-4bea23351cf2)
![Posnetek zaslona 2024-07-23 213643](https://github.com/user-attachments/assets/185e0d79-d03b-4e30-b82b-b186265cbccd)
![Posnetek zaslona 2024-07-23 213709](https://github.com/user-attachments/assets/9d8ed517-7efb-4ab3-b1b0-7c40ce24417d)
![Posnetek zaslona 2024-07-23 213735](https://github.com/user-attachments/assets/147a8faa-c8ca-41b3-9c4b-7eb4a502840a)

**Comment by DmitryPWL** [comment]
Hello all,
Another issue that relates to demostration of the LGTV graphics is that the graphic block used for match announcement and result becomes transparent in its upper part. How can this be fixed?

![Image](https://github.com/user-attachments/assets/60d23cfb-23ac-49bf-888b-ba0067c984f5)
![Image](https://github.com/user-attachments/assets/301931f1-cc43-4332-aef8-7a716bf6c841)
