### ISSUE TITLE
Generic questions about workflow and subsequent tickets

### ISSUE THREAD

**Issue by theswix** [unitedworldwrestling/arena-public#27]
**Which application you are interested about**
Arena 1.5.72.1, Scoreboard 1.2.31.1

**Your question**
Dear Arena team, @csabavirag , @bouaziz1991 , @sguenat , @eveyrat , first of all – thank you all for doing perfect job to ease the burden of secretariat and event running. It is extremely helpful and mature piece of software that sometimes needs further development and enhancements as the time goes by. From my side I’m willing to help you guys to clean up Russian translation and keep it up to date on the permanent basis even with the slightest changes, if you don’t mind. There are a few important caveats in Russian translation that need to be fixed ASAP. Anyway, let’s get down to the business . 

I helped out to run Russian National Junior Championship a few days ago and ran into several problems that really stunned me.

Prerequisites: 10 weights, 361 athletes, 3 mats. Draw was made by hand and the numbers were input into Arena manually and double-checked. All weights in general were pinned to one of the mats i.e. 61, 65 on mat A; 92, 97 on mat B etc. (except qualification  – due to large number of athletes we wanted to run event a bit faster and manually put these rounds across the mats not refreshing the matches). 
Basically Arena & Scoreboard served as “tableaux output” for the right pairing order for all the mats and to demonstrate it in the warm-up area. No actual event running was needed since Arena’s final book format unfortunately does not comply with internal final report standards of the Russian Ministry of Sports  . Yet, of course we had to fully run the event in Arena, in order to show the proper athletes’ pairing for each round on the scoreboard and in the warm-up area. And that’s where we had some show stoppers.

I will open today a few tickets, one per problem, so that each of them is treated independently and with respective screenshots. Also I’m attaching here the final book in English, and MySQL dump of this event just in case. 
[final-book.pdf](https://github.com/unitedworldwrestling/arena-public/files/6325194/final-book.pdf)
dbdump.sql.zip - _Link is made private by csabavirag_

**Comment by csabavirag** [comment]
I close this entry since we solved the relevant problems covered under other issues.
