### ISSUE TITLE
Scoreboard scaling

### ISSUE THREAD

**Issue by mikeyrus** [unitedworldwrestling/arena-public#3]
Scoreboard UWWTiming 1.2.29.27

Bad scaling of "Activity" labels on a FS mode when expanding to full screen

**Windowed by default**
![1-windowed](https://user-images.githubusercontent.com/73798069/97815768-857ff500-1ca1-11eb-9891-4f35716f3b51.png)

**Fullscreen**
![2-fullscreen](https://user-images.githubusercontent.com/73798069/97815769-86188b80-1ca1-11eb-80f3-debc0e7f0a95.png)

**Comment by bouaziz1991** [comment]
Hello @mikeyrus you can find new release here:
https://we.tl/t-AAs5bX0NA8
