### ISSUE TITLE
Russian translation needs to be fixed at least at the login and reset password pages 

### ISSUE THREAD

**Issue by theswix** [unitedworldwrestling/arena-public#30]
**Which application you are experiencing a problem with**
Arena 1.5.72.1

**Describe the bug**
Russian login page and reset password page currently have garbled encoding (please see attachment - there are screenshots with wrong encoding). Two .html files in attachment fix this problem. Everything is in UTF-8.

**To Reproduce**
1. Go to http://localhost:8080/ru/bracket
2. You're being redirected to http://localhost:8080/login with garbled Russian enconding where only checkbox and button have valid Russian encoding
2. Click there on "what-to-be-meant Reset password" link which is http://localhost:8080/ru/resetting/request
3. See garbled Russian encoding again where only reset button has valid Russian encoding
4. See errors

**Expected behavior**
Russian "login" page and "reset password" page with proper UTF-8 encoding as it states in `<meta charset="UTF-8" />` on respective pages.

**Screenshots**

[Russian_login_and_reset_pages.zip](https://github.com/unitedworldwrestling/arena-public/files/6340058/Russian_login_and_reset_pages.zip)
<img width="1440" alt="garbled_login_page" src="https://user-images.githubusercontent.com/54967199/115325388-bacbc100-a1b5-11eb-8fd7-aaf075f45d4b.png">
<img width="1440" alt="garbled_reset_page" src="https://user-images.githubusercontent.com/54967199/115325416-c7e8b000-a1b5-11eb-8be6-b8cc0c7c17ca.png">

**Additional context**
There are many other problems with Russian translation which I am willing to fix at the permanent basis if you don't mind. You can send me the respective .po or .yml or whatever is out there for correcting translation.

**Comment by csabavirag** [comment]
I checked and the Russian translation file for the login module got incorrectly converted in the past, thus weird characters are shown.
I made some tests with a fixed file and looks good, however several translations remain English due to my lack ok knowledge.
We really appreciate your help, just drop a mail to it@uww and will send the file for your review.

**Comment by theswix** [comment]
Hello, @csabavirag ! Email is sent to the it@
There is one more thing at this login page which I forgot to address. This probably has nothing to do with Russian translation, but with other translations instead. The language selector drop-down menu in the upper right corner has the wrong spelling for Russian language. Well, it is correct, but we only use this for schooling purposes of little kids to teach them right stressing in Russian words (which is difficult indeed). So Pу́сский must be Русский 
Thank you very much!
<img width="201" alt="Снимок экрана 2021-04-20 в 16 40 44" src="https://user-images.githubusercontent.com/54967199/115375562-1e76de00-a1f8-11eb-85ce-e280e5969091.png">

**Comment by csabavirag** [comment]
@theswix FYI, the login screen Russian fix has been added to the next version. We plan to release it in a few days. Thanks for your help!

**Comment by theswix** [comment]
@csabavirag Great news! Thank you very much! How about the rest of translation? Really looking forward to deal with it.

**Comment by theswix** [comment]
Fixed in 1.5.73
