### ISSUE TITLE
Connectivity between other management systems

### ISSUE THREAD

**Issue by susquach** [unitedworldwrestling/arena-public#31]
Does the Arena system have any API's to look at functionality between other management systems?

Fees/Entries paid online to one system eg: smoothcomp or revolutionise
Then information pulled automatically into Arena

Just an idea, haven't spoken with vendors of management systems to see if it is possible.

**Comment by csabavirag** [comment]
Sure, you can find the API documentation even on your Arena via http://localhost:8080/api/doc

You can find a Postman collection created from this API doc at https://github.com/unitedworldwrestling/arena-public/tree/master/Resources/Postman in case you would like to test the endpoints.
