### ISSUE TITLE
Arena upgrade problem

### ISSUE THREAD

**Issue by theswix** [unitedworldwrestling/arena-public#32]
**Which application you are experiencing a problem with**
Arena 1.5.72.1

**Describe the bug**
Unable to update to 1.5.73 Arena version in transparent and straightforward manner

**To Reproduce**
1. Launch Arena 1.5.72.1
2. Wait at least for 2 hours making sure that Arena app `crontasks` did their job
3. Check http://locacalhost:8080/bracket/changelog and see actual changelog for 1.5.73 already published
4. Check http://locacalhost:8080/jobs and see that upgrade failed
4. Notice that version 1.5.72.1. is still there in the menu and Arena app does not offer update
5. Log out and restart Arena - see the same situation
6. Go to Settings -> Operations -> Check for updates -> see the flash "New version check is completed"
7. See the same 1.5.72.1 version only available

**Expected behavior**
Correct and straightforward update completed OK

**Screenshots**
![changelog](https://user-images.githubusercontent.com/54967199/116512867-e572f380-a8f2-11eb-8e24-8ff5120b5251.jpg)
![jobs](https://user-images.githubusercontent.com/54967199/116512905-f885c380-a8f2-11eb-8383-e6fba833453c.jpg)
![operations](https://user-images.githubusercontent.com/54967199/116512916-ffacd180-a8f2-11eb-9916-474c6550b44e.jpg)

**Additional context**
On my my Macbook I successfully performed manual upgrade to 1.5.73 in cli after having exacly the same problems.

**Comment by csabavirag** [comment]
Need to see the details of the jobs with "Failed" and "Terminated" status.
Perhaps you can send me in mail or attach here to the issue

**Comment by theswix** [comment]
@csabavirag Here it is for "Failed". I think I terminated the second one by myself.

`05:20:51 ERROR     [console] Error thrown while running command
"--env=prod --verbose arena:upgrade --jms-job-id=1". Message: "Cannot
get the master version" ["exception" => RuntimeException {
…},"command" => "--env=prod --verbose arena:upgrade
--jms-job-id=1","message" => "Cannot get the master version"]

In ArenaUpgradeCommand.php line 111:

  [RuntimeException]
  Cannot get the master version


Exception trace:
  at /var/www/arena/releases/20210125082552/src/Command/ArenaUpgradeCommand.php:111
 App\Command\ArenaUpgradeCommand->execute() at
/var/www/arena/releases/20210125082552/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at
/var/www/arena/releases/20210125082552/vendor/symfony/console/Application.php:1023
 Symfony\Component\Console\Application->doRunCommand() at
/var/www/arena/releases/20210125082552/vendor/symfony/framework-bundle/Console/Application.php:97
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at
/var/www/arena/releases/20210125082552/vendor/symfony/console/Application.php:271
 Symfony\Component\Console\Application->doRun() at
/var/www/arena/releases/20210125082552/vendor/symfony/framework-bundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at
/var/www/arena/releases/20210125082552/vendor/jms/job-queue-bundle/JMS/JobQueueBundle/Console/Application.php:45
 JMS\JobQueueBundle\Console\Application->doRun() at
/var/www/arena/releases/20210125082552/vendor/symfony/console/Application.php:147
 Symfony\Component\Console\Application->run() at
/var/www/arena/releases/20210125082552/bin/console:43

In ArenaVersionMasterCommand.php line 82:

  [RuntimeException]
  Cannot get the master version


Exception trace:
  at /var/www/arena/releases/20210125082552/src/Command/ArenaVersionMasterCommand.php:82
 App\Command\ArenaVersionMasterCommand->execute() at
/var/www/arena/releases/20210125082552/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at
/var/www/arena/releases/20210125082552/src/Command/ArenaUpgradeCommand.php:51
 App\Command\ArenaUpgradeCommand->execute() at
/var/www/arena/releases/20210125082552/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at
/var/www/arena/releases/20210125082552/vendor/symfony/console/Application.php:1023
 Symfony\Component\Console\Application->doRunCommand() at
/var/www/arena/releases/20210125082552/vendor/symfony/framework-bundle/Console/Application.php:97
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at
/var/www/arena/releases/20210125082552/vendor/symfony/console/Application.php:271
 Symfony\Component\Console\Application->doRun() at
/var/www/arena/releases/20210125082552/vendor/symfony/framework-bundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at
/var/www/arena/releases/20210125082552/vendor/jms/job-queue-bundle/JMS/JobQueueBundle/Console/Application.php:45
 JMS\JobQueueBundle\Console\Application->doRun() at
/var/www/arena/releases/20210125082552/vendor/symfony/console/Application.php:147
 Symfony\Component\Console\Application->run() at
/var/www/arena/releases/20210125082552/bin/console:43

In Arena.php line 197:

  [League\OAuth2\Client\Provider\Exception\IdentityProviderException]
  invalid_request


Exception trace:
  at /var/www/arena/releases/20210125082552/vendor/unitedworldwrestling/oauth2-arena/src/Provider/Arena.php:197
 Unitedworldwrestling\OAuth2\Client\Provider\Arena->checkResponse() at
/var/www/arena/releases/20210125082552/vendor/league/oauth2-client/src/Provider/AbstractProvider.php:628
 League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse()
at /var/www/arena/releases/20210125082552/vendor/league/oauth2-client/src/Provider/AbstractProvider.php:537
 League\OAuth2\Client\Provider\AbstractProvider->getAccessToken() at
/var/www/arena/releases/20210125082552/src/RestClient/Client.php:114
 App\RestClient\Client->request() at
/var/www/arena/releases/20210125082552/src/RestClient/Client.php:143
 App\RestClient\Client->request() at
/var/www/arena/releases/20210125082552/src/Command/ArenaVersionMasterCommand.php:52
 App\Command\ArenaVersionMasterCommand->execute() at
/var/www/arena/releases/20210125082552/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at
/var/www/arena/releases/20210125082552/src/Command/ArenaUpgradeCommand.php:51
 App\Command\ArenaUpgradeCommand->execute() at
/var/www/arena/releases/20210125082552/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at
/var/www/arena/releases/20210125082552/vendor/symfony/console/Application.php:1023
 Symfony\Component\Console\Application->doRunCommand() at
/var/www/arena/releases/20210125082552/vendor/symfony/framework-bundle/Console/Application.php:97
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at
/var/www/arena/releases/20210125082552/vendor/symfony/console/Application.php:271
 Symfony\Component\Console\Application->doRun() at
/var/www/arena/releases/20210125082552/vendor/symfony/framework-bundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at
/var/www/arena/releases/20210125082552/vendor/jms/job-queue-bundle/JMS/JobQueueBundle/Console/Application.php:45
 JMS\JobQueueBundle\Console\Application->doRun() at
/var/www/arena/releases/20210125082552/vendor/symfony/console/Application.php:147
 Symfony\Component\Console\Application->run() at
/var/www/arena/releases/20210125082552/bin/console:43

arena:upgrade [-b|--branch BRANCH] [-h|--help] [-q|--quiet]
[-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi]
[-n|--no-interaction] [-e|--env ENV] [--no-debug] [--jms-job-id
JMS-JOB-ID] [--] <command>`

**Comment by theswix** [comment]
@csabavirag What I've noticed on my Macbook (another Arena installation) after being unable to update in default way is that when I ran `arena:crontasks` in console, it said something like "Latest version is already installed. Done!". Then I executed arena:upgrade and everything went smoothly - 1.5.73 was there in less than 3 min.

**Comment by csabavirag** [comment]
These logs seem to be from the time when we had network configuration issue.
The upgrade went well on this computer, thus agreed to close.
