### ISSUE TITLE
Locale in printed matter

### ISSUE THREAD

**Issue by theswix** [unitedworldwrestling/arena-public#33]
**In which application you miss a feature**
Arena 1.5.73

**Is your feature request related to a problem? Please describe.**
Full localization of all the printed matter (scoresheets, results etc.) in Arena. 
Currently the date is printed everywhere in LC_TIME=C or smth. like that, maybe in "en_EN.UTF-8" regardless of which language is used in Arena interface. 
Please see the screenshot attached.

**Describe the solution you'd like**
Printed date & time complies with user language preferences in Arena interface.

**Describe alternatives you've considered**
The most straightforward way might be incorporating respective locales and fonts (for all the languages Arena uses for its interface options) into Arena image and then check current user language preference. So, accordingly print the requested materials. 
I don't know how Arena does this exactly but I think that calling smth. like
`<?php
setlocale (LC_TIME, "ru_RU");
echo strftime ("%b %Y");
?>`
before processing respective .pdf would do it, though it needs testing.

Thank you!

**Additional context**
<img width="996" alt="wrong locale" src="https://user-images.githubusercontent.com/54967199/118585071-5d319100-b7c2-11eb-82e9-1c331fe271e3.png">

**Comment by csabavirag** [comment]
Although Arena uses a different rendering engine for PDFs, it's not impossible to achieve your request.

**Comment by csabavirag** [comment]
This feature scheduled to be available starting from the next release version (most likely in 1.5.74)
