### ISSUE TITLE
Hide competition from display

### ISSUE THREAD

**Issue by susquach** [unitedworldwrestling/arena-public#35]
**In which application you miss a feature**
Arena

**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
Competitions may be setup in Arena in advance, would like to hide events from public, eg hide old events that have been completed or scheduled events that are yet to start 

**Describe alternatives you've considered**
Have separate Arena VM for staging purposes and import (ie Master/Client import)

**Additional context**
Toggle between on and off for display or not

**Comment by csabavirag** [comment]
This is a good idea. Let's add it to the enhancement list.

**Comment by csabavirag** [comment]
This feature scheduled to be available starting from the next release version (most likely in 1.5.74)
