### ISSUE TITLE
Competition statistics

### ISSUE THREAD

**Issue by susquach** [unitedworldwrestling/arena-public#36]
**In which application you miss a feature**
Arena

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Provide statistics from weight category/athlete/style
- how many wins by pin (VFA) for all weights, or per athlete
- how many 5pts, 4pts, 2pts, 1pts scored per athlete
- total match time for athlete

**Describe alternatives you've considered**

**Additional context**
From memory this was available in the original Heracles system

**Comment by csabavirag** [comment]
It's a bit out of scope of the Arena project. I would recommend to try with some 3rd party application.
The API interface allows you to collect data from Arena and process it based on your needs.
This is more complex, but see this example: https://uww.io/wpar
