### ISSUE TITLE
Webinars???

### ISSUE THREAD

**Issue by qwer2021** [unitedworldwrestling/arena-public#37]
Hi
Will there be a continuation of the webinars?

Arena - Online results???

**Comment by qwer2021** [comment]
How to make the event (competition) available to everyone online?


![IMG_5269](https://user-images.githubusercontent.com/84749280/119561967-7cc24e00-bdae-11eb-9c27-6497d22b3e47.jpg)
![IMG_5268](https://user-images.githubusercontent.com/84749280/119561986-83e95c00-bdae-11eb-9efc-97fc94ad64b1.jpg)

**Comment by qwer2021** [comment]
**Which application you are interested about**
[eg. Arena, Scoreboard, LGTV, etc]

How to make the event (competition) available to everyone online?

![IMG_5270](https://user-images.githubusercontent.com/84749280/119568039-b77bb480-bdb5-11eb-8a71-46c4ba74d12f.JPG)
![IMG_5271](https://user-images.githubusercontent.com/84749280/119568044-b8ace180-bdb5-11eb-8ed2-55daf83f8899.JPG)
![IMG_5272](https://user-images.githubusercontent.com/84749280/119568045-b9457800-bdb5-11eb-94a6-607845f13a60.JPG)

**Comment by mostafaaghayari** [comment]
Hi, I am Mostafa from Iran and I have a problem with running the LGTV program and I cannot run the program. Shows the following errors when running the program and does not show the names of the athletes Please send me if you have an instructional video or instructions Thank you

> 
![LGTV](https://user-images.githubusercontent.com/82810245/119603294-24b53700-be02-11eb-85a5-eb451a8b7438.jpg)

**Comment by csabavirag** [comment]
@qwer2021 do you mean about how to setup a server which acts as the "synchronisation remote" where you sync events to and make this server publicly available on the Internet? Similar to https://arena.uww.org ?

**Comment by qwer2021** [comment]
> @qwer2021 do you mean about how to setup a server which acts as the "synchronisation remote" where you sync events to and make this server publicly available on the Internet? Similar to https://arena.uww.org ?

Yes

**Comment by qwer2021** [comment]
Yes
wondering how to do it?

**Comment by qwer2021** [comment]
> I think it should not be a problem. Let's collect topics here and if there is enough subject for a session (or more :) ), we will schedule.
> Please be as descriptive as possible with your request.



> @qwer2021 вы имеете в виду, как настроить сервер, который действует как "дистанционный синхронизация", где вы синхронизируете события и делаете этот сервер общедоступным в Интернете? Похоже на https://arena.uww.org?


Yes 👍

**Comment by qwer2021** [comment]
> @qwer2021 do you mean about how to setup a server which acts as the "synchronisation remote" where you sync events to and make this server publicly available on the Internet? Similar to https://arena.uww.org ?

Yes 👍

**Comment by csabavirag** [comment]
At the moment there is no official document on how you should setup an internet facing Arena to your users, since the solution UWW uses is part of an enterprise grade solution. Due to the nature of that setup, it cannot be stripped down to Arena only, thus we can’t build a training session for your benefit.

However there are people around there who has already made progress on their individual solutions and perhaps willing to share their experiences with others. Therefore I think the best would be to create a dedicated discussion to this topic where others can chime in and together we could maintain a “live” document with different solutions that others can chose from.
