### ISSUE TITLE
LGTV Error

### ISSUE THREAD

**Issue by csabavirag** [unitedworldwrestling/arena-public#38]
**Which application you are experiencing a problem with**
LGTV

**Describe the bug**
Hi, I am Mostafa (@mostafaaghayari) from Iran and I have a problem with running the LGTV program and I cannot run the program. Shows the following errors when running the program and does not show the names of the athletes Please send me if you have an instructional video or instructions Thank you

> 
![LGTV](https://user-images.githubusercontent.com/82810245/119603294-24b53700-be02-11eb-85a5-eb451a8b7438.jpg)

**Comment by csabavirag** [comment]
Hi @mostafaaghayari, could you disable the Swiss Timing option? LGTV -> Configuration -> General Settings -> SwissTiming? should be unchecked.

**Comment by mostafaaghayari** [comment]
Hi Yes, you must remove the Swiss scheduling check. If this is done, the timer will no longer be displayed on the screen.
If you have the full LGTV sting training video, please put it in the UWW IT Webinars - Arena Training Series

**Comment by mostafaaghayari** [comment]
![uwwtiming](https://user-images.githubusercontent.com/82810245/120091685-bc789500-c122-11eb-8a7b-727e958c5e17.jpg)
![LGTV](https://user-images.githubusercontent.com/82810245/120091689-c7332a00-c122-11eb-9fd1-773f3524212a.jpg)

**Comment by csabavirag** [comment]
Did you try to follow webinar "Arena Training Series - Companion applications" available at https://uww.org/webinars?field_webinar_type_target_id=2024&field_datetime_value=All ? The LGTV section starts at 28:25 in the video.

It's important to verify your Windows firewall settings, those can block the communication between UWWtiming scoreboard application and LGTV.

If that still does not work, send a mail to our IT mailbox and we will contact you for troubleshooting.

**Comment by mostafaaghayari** [comment]
First, I would like to appreciate for your help and kindness. Actually, based on the instructional webinar, the names and nationalities of the participants in LGTV were done. But when we want to start from the scoreboard, the record is not done automatically in OBS. Also, the relevant page is not shown in the first part of the competition in introducing the athletes. (Refer to min. 42 in “Arena Training Series chapter5 Companion applications –uwwtiming ,
![abc](https://user-images.githubusercontent.com/82810245/120977642-ccc6ea80-c788-11eb-9239-42a4b279a274.png)
LGTV ” )

**Comment by bouaziz1991** [comment]
Dear @mostafaaghayari 
Thank you very much for your contact.
Please download the latest version of LGTV, you can check the OBS box if you use OBS to record the matches, especially do not check the SwissTiming box, then you must select the repeater you are going to use to save the videos of the matches , update the streaming server url and streaming key if used.
Please make sure your screen resolution is 1920x1080 and zoom is 100%.
I remain at your disposal for next questions.
Have a good day.

**Comment by mostafaaghayari** [comment]
Thanks to the instructions for running the LGTV program, the current program of names, nationalities and other specifications can be seen on the LGTV, but the athletes and challenge introduction page is not running yet. Please help me with the settings and how to use the LGTV in live TV broadcasting. .
![arena-LGTV](https://user-images.githubusercontent.com/82810245/121849404-23a85480-cca0-11eb-80b4-43eedc421d6d.jpg)



Uploading 02.mp4…

**Comment by mostafaaghayari** [comment]
HI,
It seems that the table of beach competitions has not changed according to the latest rules, while the latest version of Arena software 1.5.73 is also installed, please help if possible.

**Comment by csabavirag** [comment]
Hi @mostafaaghayari , please always create a new issue if your problem is different from any other opened issue.
I created one for you now (#42) where the beach wrestling issue can be tracked and discussed.

Let's keep this issue for your LGTV problem.

**Comment by mostafaaghayari** [comment]
Hello, good morning, Dear .Bouaziz
Thanks again for the guidelines for running the LGTV program. Currently, the program names, nationalities and other specifications can be seen on the LGTV, but the athletes and challenge introduction page is not running yet. Please help me with the settings and how to use the LGTV in live TV broadcasting. Software version used.
LGTV 1.2.7.5
OBS Studio 27.0.1
uwwtiming 1.2.31.1
Forgive me if there is a problem with spelling or writing.
![arena-LGTV](https://user-images.githubusercontent.com/82810245/122184325-5b321f00-cea1-11eb-9b15-3fedf986008a.jpg)

https://user-images.githubusercontent.com/82810245/122184480-7e5cce80-cea1-11eb-9c4c-109bebb990ff.mp4

**Comment by csabavirag** [comment]
I don't know if it makes sense, but a few commends after watching your video:
- you chose the loopback adapter in Scoreboard app (video 0'37")
- also you set the Arena server 127.0.0.1 
I would recommend to chose another interface (either WiFi or LAN) here and most likely you will have to type the same IP address what you can see after WiFi (192.168.43.22) to the top of the window. So the Arena server address would look like this case:
[http://] 192.168.43.22:8080 [/api...]

Perhaps it's worth to give a try.

**Comment by mostafaaghayari** [comment]
Hello, thanks for the support and guidance which you provided about launching LGTV software. Now, all the problems have been resolved, and after the settings related to the resolution, all the relevant information will appear. But there are two below problems:
1-	To use ShuttlePro; when I download the file "LGTV.e.pref" from the shuttleprov2 profile / config section, it is empty and shows the file size as zero. Please, upload the relevant file if it is possible.
2-	Also, provide the necessary settings in using LGTV for TV broadcasting, please.
[2021 Wocs S 001 مصطفی آقایار . میلاد فرزانه . Gr 97(1)-1.zip](https://github.com/unitedworldwrestling/arena-public/files/6731234/2021.Wocs.S.001.Gr.97.1.-1.zip)
[LGTV.e.zip](https://github.com/unitedworldwrestling/arena-public/files/6731240/LGTV.e.zip)

**Comment by bouaziz1991** [comment]
Hello @mostafaaghayari 

This is the pref file for **Shuttle Pro v2** https://we.tl/t-PAPAKshsO2

To use LGTV for TV production you can use 

- **1 link** to video mixer with chroma key
**or**
- **2 links** to video mixer (2 windows machine running LGTV) and set 1st machine as Alpha Key and second one as Alpha Fill in LGTV settings, also set both machine to listen the same mat (A) or (B)...

**Comment by mostafaaghayari** [comment]
Hello good time
Thanks for the help, please help to fix the program execution error 
[capture-2.zip](https://github.com/unitedworldwrestling/arena-public/files/6794566/capture-2.zip)

**Comment by mostafaaghayari** [comment]
Hello good time
Thanks for the help, please help to fix the program execution error
[capture-2.zip](https://github.com/unitedworldwrestling/arena-public/files/7038230/capture-2.zip)

**Comment by bouaziz1991** [comment]
Hello @mostafaaghayari 

a new version of LGTV is ready here ;) https://github.com/unitedworldwrestling/arena-public/tree/releases/lgtv

**Comment by farismounel** [comment]
> 
![Screenshot (2)](https://user-images.githubusercontent.com/95596082/196593306-b9b2e568-63c3-4fe2-99cc-6ce1b71e8a7b.png)
why the LG TV can.t shoe the configuration tab?

**Comment by mostafaaghayari** [comment]
.

**Comment by Aditya-Bukki** [comment]
> > 
> 
> ![Screenshot (2)](https://user-images.githubusercontent.com/95596082/196593306-b9b2e568-63c3-4fe2-99cc-6ce1b71e8a7b.png) why the LG TV can't show the configuration tab?

Hello brother,

Same problem is happening with me like you, when i am starting the LGTV software, its appearing full GREEN SCREEN with no start or configuration option.

I want to fix the problem, can you please help me, 

your's LGTV is running now in proper manner ?

**Comment by mostafaaghayari** [comment]
Hello
LGTV will not work properly until it detects the scoreboard IP.

**Comment by ybouaziz** [comment]
Hello @mostafaaghayari 

Your issue is fixed in the last version of LGTV.

Have a nice day!
