### ISSUE TITLE
Beach wrestling bracket problem

### ISSUE THREAD

**Issue by csabavirag** [unitedworldwrestling/arena-public#42]
![beach bracket](https://user-images.githubusercontent.com/82810245/121870683-863d3700-cd18-11eb-9fda-e02e193a704b.png)
[beach rules.pdf](https://github.com/unitedworldwrestling/arena-public/files/6647011/beach.rules.pdf)
HI,
It seems that the table of beach competitions has not changed according to the latest rules, while the latest version of Arena1.5.73 is also installed, please help if possible.

_Originally posted by @mostafaaghayari in https://github.com/unitedworldwrestling/arena-public/issues/38#issuecomment-860499458_

**Comment by csabavirag** [comment]
Can you create a screenshot about this weight category?
1. Go to Weight Categories
2. Chose 80 kg under Men's Beach Wrestling
3. Click on the Pencil icon (Edit) right next to the red, Delete button
4. Take a screenshot

I just checked and a beach wrestling weight category created the proper layout (groups) according to the rules book.

**Comment by mostafaaghayari** [comment]
Hello good time
Thanks to the unwavering guidance, unfortunately, when creating a new event, instead of selecting bachwrestling in the tournament type, the single bracket was selected incorrectly, and the problem was fixed after the correction.

**Comment by csabavirag** [comment]
Good to hear it was just a minor typo.
Correct, either you can setup your event by choosing `beachwrestling` as `Tournament Type` under the `Competition Format` section, or you can even update a weight category later (one-by-one), by editing it and changing the `Tournament` to `beachwrestling`.
