### ISSUE TITLE
Remove and return the competition mat

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#43]
Hello Mr. csabavirag Thanks for answering the questions. If one of the competition mats is removed by mistake during the competition, is there a way for the twice removed mattress to return to the table with all the competitions?

   -Win 10
 - Browser [chrome]
 - Version 91.0.4472.106 (Official Build) (64-bit)
 -Arena 1.5.73

![Remove and return the competition mat](https://user-images.githubusercontent.com/82810245/122184069-1a3a0a80-cea1-11eb-9789-aaee5fd9d113.jpg)

**Comment by csabavirag** [comment]
In Arena 1.5.71 (22-Feb-2021) Arena introduced an improvement "_Fix: Matches are relocated to other mat if their mat is deleted_". That means, if you accidentally delete a mat, the matches assigned to this deleted mat would become moved to another mat (before that, those matches simply disappeared).

So if you delete a mat, chose simply the "Add Mat" button to (re)create, then move the desired matches to the newly added mat.
> ![image](https://user-images.githubusercontent.com/10976654/122212585-4dcc6300-cea8-11eb-8b38-229b558f7690.png)

Btw, I believe (and hope :) ) your 2nd screenshot was just created in a "Paint" like program and you just graphically cleared the "Mat B" area. And that's the only reason why you don't have the Session's action buttons (Results|Add Mat|Edit|Program) visible.

**Comment by mostafaaghayari** [comment]
Hello, thank you for your helpful and valuable tips. When the match is removed from one of the mats, the match will not be moved to the other mats. Please pay attention to the prepared video. 

https://user-images.githubusercontent.com/82810245/122284431-cfe97580-cf02-11eb-84cd-7c62984d1701.mp4

**Comment by csabavirag** [comment]
Thanks for the details and sorry for the trouble.
This problem is accepted as a bug. In the mean time a fix has already been developed so you should expect the correct behaviour in the next release.

https://user-images.githubusercontent.com/10976654/122393240-f647f900-cf74-11eb-90b2-530e12dcc410.mp4

**Comment by mostafaaghayari** [comment]
Dear Mr. csabavirag, thank you very much for your support and guidance

**Comment by csabavirag** [comment]
Your most welcome. I also thank you for finding bugs and helping to make Arena better :)
I close this thread now.

**Comment by mostafaaghayari** [comment]
Hi, according to the uploaded video, the match was removed, but unfortunately it does not seem to work properly in my system.
Would you please, help and guide me about the problem.
[Remove and return the competition mat #43.zip](https://github.com/unitedworldwrestling/arena-public/files/6731256/Remove.and.return.the.competition.mat.43.zip)
