### ISSUE TITLE
pdf output error

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#44]
Hello
Thanks, after updating the software to version 1.5.75.1, the pdf output has an error. Please help to fix the error.

https://user-images.githubusercontent.com/82810245/126288645-7ab6493f-d0da-4c12-b6a8-da220a1bdae2.mp4

**Comment by mostafaaghayari** [comment]
Dear Casba
Hello,Thank you very much for your help in solving the problem .

**Comment by csabavirag** [comment]
Thanks for the confirmation Mostafa!
There seemed to be a network problem during the update and the new modules required for printing were not installed. Installing them manually fixed the problem.

Closing the ticket now.
