### ISSUE TITLE
Team and individual results of matches

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#45]
Hello and thanks, in order to be able to see team and individual results of matches in a table, is it possible to create a table similar to the attached file in the Arena software?
[Final table ranking.pdf](https://github.com/unitedworldwrestling/arena-public/files/6910844/Final.table.ranking.pdf)

**Comment by csabavirag** [comment]
Working on it

**Comment by csabavirag** [comment]
You can find it under the Sport Event's Print menu starting from 1.5.75.5
