### ISSUE TITLE
Training class

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#47]
Hello, is it possible for you to hold a training or re-training class about the ARENA software by connecting to the scoreboard and LGTV before launching International competitions, Europe, etc.?

**Comment by csabavirag** [comment]
There is a work on a UI redesign for LGTV. Once it's completed, we will plan a new training for the companion application integrations including the new features. There is no ETA set at the moment, but progressing well :)

**Comment by mostafaaghayari** [comment]
Thank you Mr. Csaba.
