### ISSUE TITLE
Add the tournament logo to the Final Book

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#49]
Hi Good time ,Is it possible to create a menu to add the tournament logo to the Final Book (all pdf)? .

**Comment by csabavirag** [comment]
Yes, at the moment there is no user interface to upload logo for any event. We will triage the request.

**Comment by mostafaaghayari** [comment]
thank you very much

**Comment by csabavirag** [comment]
New version is released. Please upgrade.

**Comment by mostafaaghayari** [comment]
Hello, thank you very much
