### ISSUE TITLE
Can`t upload custom flags

### ISSUE THREAD

**Issue by euhenpetrov** [unitedworldwrestling/arena-public#5]
**Which application you are experiencing a problem with**
[eg. Arena, Scoreboard, LGTV, etc]   
Arena

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
                              OS: [e.g. Windows 10
 - Browser [e.g. chrome, edge]    
![Q A for IT](https://user-images.githubusercontent.com/67595896/99780730-8cbb5580-2b1f-11eb-85c3-099180a0a2a5.png)
 chrome

**Additional context**

**Comment by csabavirag** [comment]
Sorry for the inconvenience. That's a typo on the UI, and the current version only supports 2MiB.
If you have larger flag collection, create multiple ZIP files fitting to the size limit. Don't forget to remove the clean.txt from every other ZIP file than the first one. That will allow you to "append" new flags.

You may also want to reduce the size of the flag files until larger ZIP is accepted.

**Comment by csabavirag** [comment]
@euhenpetrov Arena version 1.5.70 has the fix included. You may want to upgrade and test.

**Comment by euhenpetrov** [comment]
Hi Chaba! Thank you for the arena webinars, it is a pity that the latest
topics were not covered like the API. I used version 1.5.53 before version
1.5.70 and during the upgrade I had a problem due to which I had to go back
to the old version 1.5.43.2. Now all my attempts to update do not lead to
anything. I carefully read the instructions in the github and followed
them. I am sending you screenshots of everything that happened on my
computer. Perhaps you can help me. Thank you!

пн, 25 янв. 2021 г. в 15:41, csabavirag <notifications@github.com>:
