### ISSUE TITLE
  Top team and tournament rankings 

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#51]
Hi
In team competitions, for example, four groups of three teams, after identifying the top teams in each group to determine the top team and rank the competition, the app arena no longer determines the continuation of the competition. Is there a solution please help. 

https://user-images.githubusercontent.com/82810245/131454809-ff22db1b-a2c4-47aa-b27a-5d5444bd94c1.mp4

**Comment by csabavirag** [comment]
Interesting. Based on your recording, this event seems to have all the Pool fights completed. Arena is creating matches for the finals only if every match is completed under the qualification session.
Can you mail me the dump generated via Settings->Operations->Export Database to reproduce the problem on my side?

**Comment by mostafaaghayari** [comment]
Hello and thank you Mr. csaba

**Comment by mostafaaghayari** [comment]
Hello and thank you Mr. csaba

**Comment by mostafaaghayari** [comment]
Thanks Mr. csaba Top team and tournament rankings number (# 51) closed
incorrectly, please check and correct

‪On Wed, 1 Sept 2021 at 11:39, ‫مصطفی آقایاری‬‎ ***@***.***> wrote:‬

> Hello and thank you Mr. csaba
>

**Comment by mostafaaghayari** [comment]
Thanks Mr. csaba Top team and tournament rankings number (# 51) closed
incorrectly, please check and correct

‪On Wed, 1 Sept 2021 at 11:47, ‫مصطفی آقایاری‬‎ ***@***.***> wrote:‬
