### ISSUE TITLE
Something wrong with arena or with my pc

### ISSUE THREAD

**Issue by euhenpetrov** [unitedworldwrestling/arena-public#53]
**Which application you are experiencing a problem with**     arena 1.5.75.5  
[eg. Arena, Scoreboard, LGTV, etc]

**Describe the bug**

**To Reproduce**
1. Go to '...'                             arena navigate panel
2. Click on '....'                            check match (red color of match)
4. See error                                      504

**Expected behavior**

**Screenshots**
![Screenshot_8](https://user-images.githubusercontent.com/67595896/133039095-d23cdbff-779b-476e-a9d9-b7fb287d3173.png)

**Desktop (please complete the following information):** 
 - OS: [e.g. Windows 10]                                                                                      Windows 10
 - Browser [e.g. chrome, edge]                                                                             Chrom

**Additional context**
Add any other context about the problem here.               when I reload arena sometimes it runing norm for a few minutes but in 
                                                                                            match  sheet when I check it sometimes I see the wrong points from 
                                                                                             uwwtiming like 5 5 5 5 5 5 5 5 5 5 5................. but man who controls 
                                                                                              uwwtiming doesn't put down thees points

**Comment by csabavirag** [comment]
@euhenpetrov reported that Arena was moved to another computer and it works fine.
Closing due to a local issue
