### ISSUE TITLE
Change pdf font

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#54]
Hello and thanks for creating table # 45 (print top10 result) When selecting the Persian language, the fonts of the table are not readable. Please correct the font of the above table like the fonts of other pdfs.
[print top10 result.pdf](https://github.com/unitedworldwrestling/arena-public/files/7270909/print.top10.result.pdf)
[ranking.pdf](https://github.com/unitedworldwrestling/arena-public/files/7270910/ranking.pdf)

**Comment by csabavirag** [comment]
Thanks for reporting the problem. I mark it as a bug and will be fixed soon.

**Comment by csabavirag** [comment]
Problem is fixed in Arena version 1.5.77
