### ISSUE TITLE
Webinar about Arena API interface

### ISSUE THREAD

**Issue by euhenpetrov** [unitedworldwrestling/arena-public#60]
Hello Csaba. As far as I remember, you planned but did not conduct a seminar on the API topic. Are you planning to cover this topic in a webinar?

**In which application you miss a feature**
[eg. Arena, Scoreboard, LGTV, etc]

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by csabavirag** [comment]
I'm happy to say that the video content of our 6th chapter under the Arena Training Series has been published under the IT Webinars section.

**Comment by csabavirag** [comment]
Sorry @euhenpetrov there was a glitch in the process :) The video is uploaded again.
If it's still stops at 17 mins, the playlist might be cached, so try to change the resolution (at the bottom right corner of the video window).

**Comment by mostafaaghayari** [comment]
Hi I thank the IT group and Mr csabavirag.
