### ISSUE TITLE
Issue on Referees registration

### ISSUE THREAD

**Issue by palvespt** [unitedworldwrestling/arena-public#64]
Dear UWW IT Team,

Please check the issue below regarding the referees tab.

**Which application you are experiencing a problem with**
[Referees tab]

**Describe the bug**
After registered the referees on the competition i changed the tab to create the competiton matches. When i got back to the referees tab all referee were missing. Please check the prtscr below.

**To Reproduce**
1. Go to 'referees.'
2. Click on 'add'
3. create a new referee and click save
4. repeat the process until complete

**Expected behavior**
Referees list should be visible since that they were registred

**Screenshots**
Prtscr attached

**Desktop (please complete the following information):**
 - OS: [ Windows 10]
 - Browser [ chrome]
 - Version [96.0.4664.45  - 64 bits]
 - Arena version - 1.5.77

**Additional context**
Please note that this also happened on the previous version. At the time i was registering the referees on a real competition.

![referees](https://user-images.githubusercontent.com/94856801/142899303-515aae2e-f8b6-4b70-ac77-2d9b7098d637.JPG)

Thanks in advance for your support.

Pedro Alves

**Comment by csabavirag** [comment]
Can you export your database (Settings->Operations->Export Database) and attach here?

**Comment by palvespt** [comment]
Yes , sure.

Please check below.

Btw, i registered 6 referees.

Thanks for your support.

Pedro Alves

[dbdump.sql.zip](https://github.com/unitedworldwrestling/arena-public/files/7583844/dbdump.sql.zip)

**Comment by csabavirag** [comment]
Thanks for the dump! Did you see new referees on the list right after you added them?

based on the DB snapshot, my assumption is the following:
You added all the 6 referees to the list manually. All of them were set as POR as the referees' country. At the end, all the 6 referees were supposed to be displayed at the referee tab.
After this, you might (accidentally) deleted the POR team from the system, which invoked the removal of your referees.

My assumption is based on the same removal times in the database for the referees and the team (POR).

Can you confirm if this happened? Also, if you can reproduce the behavior again, please share what you did after "Step 4".

**Comment by palvespt** [comment]
Hi Csaba,
Indeed you are totally right.
I saw the referees after i added them but then i remove the POR team because i only have clubs on the teams and forgot about the correlation with the referees.
Meantime i already reproduced and had the same result, this means that the referees were removed again.
Thanks for your support Csaba!
