### ISSUE TITLE
Importing athlete, 

### ISSUE THREAD

**Issue by NumanYayici** [unitedworldwrestling/arena-public#66]
Dear Csaba 
When i reimport athletes from excel it Doubles athlete agein. İ did import without putting draw numbers. 
Thanks 
Numan

**Comment by csabavirag** [comment]
Numan, if you want to avoid duplications on Person records across multiple imports (for the same or even a different event), you must use one of the "ID" fields within the import sheet.
Chose either the "Athena Print ID" or "Custom ID" (recommended for Federations) columns to assign a unique ID to every person. This way the import process will be able to identify an existing Person in the database and will not create a new record at every import.
Without using the CustomID there is no way to differentiate two Person with the same name from each other.

CustomID value is free text, so you can generate it per your needs. For example you can use your athlete's Federation Registration Number here, or any other way which guarantees you to a unique identification of a Person at your competitions.

**Comment by NumanYayici** [comment]
Thank you Csaba
