### ISSUE TITLE
Adding weight catagories for u13 

### ISSUE THREAD

**Issue by NumanYayici** [unitedworldwrestling/arena-public#67]
Hi Csaba
İ tried to add weight catagories from sports config but couldn't save Thé weight catagories. 

Thanks 
Numan

**Comment by csabavirag** [comment]
Hi Numan,
What error did you get when tried to create your custom configuration?

I was able to add a test category without any problem in the Text Editor:
![image](https://user-images.githubusercontent.com/10976654/144588073-f15a162f-ffea-4be2-89f1-1829c31d574d.png)

**Comment by NumanYayici** [comment]
Thank you Csaba
