### ISSUE TITLE
create ID card

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#68]
Hi
Can App Arena information be used to create an ID card?

**Comment by csabavirag** [comment]
It is possible to query athletes registered under a SportEvent in Arena from a 3rd party application via Arena's API interface. This app can then generate any output (eg an accreditation card) from the response it receives from Arena.

Btw, this is a good use case for the API webinar (https://github.com/unitedworldwrestling/arena-public/issues/60)

**Comment by behzadbadr** [comment]
hi

**Comment by mostafaaghayari** [comment]
سلام وقت بخیر

**Comment by behzadbadr** [comment]
سلام مخلصیم

در تاریخ پنجشنبه ۲۷ اکتبر ۲۰۲۲،‏ ۱۳:۱۷ mostafaaghayari <
***@***.***> نوشت:
