### ISSUE TITLE
TOP 10 LİST FULL NAME

### ISSUE THREAD

**Issue by dur386** [unitedworldwrestling/arena-public#69]
Dear Jaba Good evening from Turkey. If the name and surname are long in the Arena TOP 10 List, the list is not written in full. Is it possible to have FULL NAME while writing the list.Also, we need to write the chief referee and ruler referee information under the TOP LIST. Pdf does not allow this. I would appreciate your help. Good evening.
![Ekran Görüntüsü (9)](https://user-images.githubusercontent.com/79795576/144914285-728d9ef0-04c7-4536-a76f-91f52a6fb532.jpg)

**Comment by csabavirag** [comment]
Yes, the TOP10 ranking report uses the "Short Name" attribute of a person, which is created from LastName + First letter of FirstName + "." at the end.
This was required to keep all the columns on one page. Imagine, attending couple of athletes with names such as "Alejandro Rodrigues De la Vega" or "Abdellatif Mohamed Ahmed Mohamed" would allocate a lot of space within the table, which may cause a crop of the last columns.
In your case, I believe you added those People with "full name" to Arena with ALL capitals. The application detects the family name as you entered with capitals (or if you don't use capitals, the last name will be stored as family/lastname). So entering "James BOND" or "BOND James" will both create a person record with FirstName = "James" LastName = "Bond". However if you enter a person as "JAMES BOND", then the FirstName will be empty, Lastname = "James Bond". This way you will see the "Short Name" as "JAMES BOND .", so it seems like the full name is displayed, but in reality, it's not. You just entered that person in a wrong way.
Does this make sense to you?

Btw, we use the same "Short Name" on the brackets as well (or even in Scoreboard). That was a compromise to be able to accept long names in Arena, but fit them where it's needed.

With regards to the referee question, could you elaborate a bit more? Do you need the paper signed by the referees? Some PDF editors allow you to add certain objects to the document (like a signature). Or if you print out for your static records, it can also be signed.
