### ISSUE TITLE
Doesn't work the buttom "caution" in last version of scoreboard

### ISSUE THREAD

**Issue by euhenpetrov** [unitedworldwrestling/arena-public#7]
**Which application you are experiencing a problem with**    Scoreboard
[eg. Arena, Scoreboard, LGTV, etc]

**Describe the bug**
A clear and concise description of what the bug is.        Doesn't work the buttom "caution" in last version of scoreboard
![Screenshot_4](https://user-images.githubusercontent.com/67595896/101604894-3482bf80-3a0a-11eb-9ef1-4d98f4b96278.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**       w10
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome, edge]

**Additional context**

**Comment by csabavirag** [comment]
Thanks @euhenpetrov for reporting the issue. Check [main page](https://github.com/unitedworldwrestling/arena-public) for the new version (1.2.30.4) which solves the problem.
