### ISSUE TITLE
What is the new overtime property on weight categories added to a sport event? (Rest API)

### ISSUE THREAD

**Issue by futaz** [unitedworldwrestling/arena-public#70]
**Which application you are interested about**
Arena v1.5.78.1, Rest API

**Your question**
I have upgraded Arena from 1.5.70.2 to 1.5.78.1 and it seems there is a breaking change in the rest API.
When I try to create a new SportEventWeightCategory (`POST /api/{_format}/weight-category/{sportEventId}`) I get an error because the new `overtime` property is required.

When I add a weight category to a sport event on the web, it's value will be `0`.
Could you tell me what is this property?
Is it OK if I create SportEventWeightCategories with hardcoded `overtime = 0` via rest API?

**Comment by csabavirag** [comment]
I some sports like Grappling, there is an overtime (1 round in total and in case of equality, an addition x seconds overtime is organised to find a winner).
This new attribute manages this behavior. Hardcoding it to `overrime = 0` will mean, none of the weight categories your application creates in Arena will have overtime enabled.

Btw, this parameter is not used in Arena's "business logic", it just exposes to UWWtiming (Scoreboard), which acts accordingly.

**Comment by futaz** [comment]
OK, I get it. After consulting our customer, it seems this is irrelevant for us, so `0` should be fine. Thank you!
