### ISSUE TITLE
 instructions or algorithms for the new bracket

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#73]
Hi Csaba، if you have any instructions or algorithms for the new bracket, please help

**Comment by csabavirag** [comment]
You can find the sample brackets published at https://uww.org/governance/regulations-olympic-wrestling (Navigation: UWW Main page->Governance->Regulations->Olympic Wrestling).
These give you an overview on the bracket layouts for any participants (up to 36 participants).

You can also watch a video which details the process at our Webinar page (https://uww.org/training-education?field_webinar_type_target_id=2024&field_date_range_time_value%5B%5D=2). Search for the entry 01-Feb-2022

**Comment by mostafaaghayari** [comment]
Thank you so much

**Comment by mostafaaghayari** [comment]
Thank you so much
