### ISSUE TITLE
ARENA PAIRING PROBLEM

### ISSUE THREAD

**Issue by dur386** [unitedworldwrestling/arena-public#74]
Hi Csaba;

Greetings from Turkey; In versions prior to 1.78.1 in the arena, there was no HEAD SEED application when MATCHING. However, in 1.78.1, it does not just do it as seed, it makes a pointless match. Athletes who will make the pre-qualification must match from the lower group.Is this a problem or a rule change? the example I posted is a comparison of 1.5.76.3 and 1.5.78.1.If it is a rule change, how will we implement it in Turkey? countries may have different practices.This problem is especially in the qualifying competitions.

![Ekran Görüntüsü (28)](https://user-images.githubusercontent.com/79795576/152647003-9a18d009-adf3-4c5b-8899-e9dd2fdfc1f2.png)

![Ekran Görüntüsü (29)](https://user-images.githubusercontent.com/79795576/152647007-57138b67-4293-4f9f-b20e-01bfb8cbcf1d.png)

**Comment by csabavirag** [comment]
Hi, along with several other rule changes, the bureau has also approved a better balance on the qualification rounds across the bracket.
You can find it in [25.01.2022 - New adjustments to the International Wrestling Rules](https://cdn.uww.org/s3fs-public/2022-01/05_wrestling_rules.pdf?VersionId=zklKxc7xrr1lANM3L9N5E5.4DMjM306h) published at https://uww.org -> Governance -> Circular letters -> Olympic Wrestling

Also, check issue #73 for additional details.

**Comment by dur386** [comment]
Csaba: In the latest version, do we apply PER SERIAL for all mappings. But we do not do PER SERIAL in Turkey.How will we use version 1.5.78.1 in the ARENA without SEEDING? can you reply urgently please .

**Comment by csabavirag** [comment]
I think you got clarification from @NumanYayici but of course Arena still supports creating bracket without seeds.
