### ISSUE TITLE
error when entering the draw 

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#75]
Hi Csaba، 
Sometimes there is an error when entering the draw and the system closes. Please help.
![IMG-20220209-WA0058](https://user-images.githubusercontent.com/82810245/153180932-ce615197-1a19-40c6-8c67-acd0a0994c6c.jpg)
dbdump.sql.zip - detached from the message

**Comment by csabavirag** [comment]
Hi Mostafa,
I'm sorry for that.
What do you mean under "sometimes"? Some weights work, others don't? Or there is only 1 specific weight category fails?
If only 1 fails, did you do any specific to this weight category before going to the Draw menu?

**Comment by mostafaaghayari** [comment]
The error is in an age group and it seems that when the number of draws is 35 or more, the system is closed and you have to log in again.

**Comment by csabavirag** [comment]
I was able to reproduce the problem locally. Fix is on the way... :)

**Comment by mostafaaghayari** [comment]
Thank you so much

**Comment by csabavirag** [comment]
Arena 1.5.79 is out. Please upgrade and check if that works for you as well.

**Comment by mostafaaghayari** [comment]
Hi csaba
Thanks, the problem has been solved.
