### ISSUE TITLE
We cannot send a match to the main server from the referee's table.

### ISSUE THREAD

**Issue by dkaya60** [unitedworldwrestling/arena-public#81]
Hello Csaba,
In general, in 2-day competitions, there is a problem in sending the matches to the main server on the scoreboard in REPESAJ matches. The machine freezes. We cannot send matches from the referee tables to the main server. Could this have something to do with the REPESAJ matches? Why are we having problems?

**Comment by csabavirag** [comment]
Few questions: 
- Did this happen with any repechage match, or only with certain ones?
- Did this happen on all your Scoreboard computers (if you were using more than 1)
- Can you reproduce it by creating a new event?

**Comment by dkaya60** [comment]
In general, in competitions where the number of athletes is high, we cannot send a match from the referee tables to the main server, the scoreboard program gets locked - it mostly occurs in repechage matches. This is not just a problem I've encountered. Often the main server computer is completely locked. We need to close and restart ARENA.

Did this happen with any repechage match, or only with certain ones? 
**Mostly in matches where the number of Athletes is very high
Did this happen on all your Scoreboard computers (if you were using more than 1)
**This has happened on all of your Scoreboard computers, we generally use multiple computers and the problem occurred.

**Comment by dkaya60** [comment]
Also, Csaba 4-character match numbers do not appear in brackets, for example 1116 match numbers appear as 111

![Ekran Görüntüsü (51)](https://user-images.githubusercontent.com/79795576/163471272-7a0b01ae-d9aa-48fe-9151-1945d0cdd819.png)

**Comment by csabavirag** [comment]
With regards to the freezes/slowness: What is your computer's hardware specification (the host computer where you run VirtualBox)?
It seems to me you are having lack of CPU and RAM for your virtual machine.

**Comment by dkaya60** [comment]
Dear Csabavirag, I am playing the competitions with this computer. It is top level in terms of features. However, when the number of athletes is around 650-700. I cannot send a match to the main server. The scoreboard system is locked. I have to turn the VirtualBox off and on. When there are over 1000 players, the arena almost never works. I need a solution. Thank you.
 Dursun KAYA-  Turkey
Device name :DESKTOP-11VPNRG
Processor : Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz 2.60GHz
Installed RAM :16.0 GB (usable: 15.9 GB)
Device ID C7BCD93A-950B-43A3-8B95-D56722212669
Product ID 00330-80000-00000-AA388
System type :64-bit system, x64-based
Pen and tapping This display has pen input or no tap input


![Ekran Görüntüsü (52)](https://user-images.githubusercontent.com/79795576/164292623-c0bb02b5-63dd-41e6-9dad-e717b4bab055.png)

**Comment by csabavirag** [comment]
@dkaya60 thanks for the details. One more thing to clarify please.
Do you remember if you tried to print brackets/results or anything which generated error in Arena prior to the "freeze"? I mean were there any error message (due to long running operations) in Arena admin before you started seeing the unresponsive state of Scoreboard and Arena admin interface?

**Comment by dkaya60** [comment]
Dursun, the fight number problem is going to be fixed in the next version
Thank you Csabavirag.

**Comment by dkaya60** [comment]
@dkaya60 thanks for the details. One more thing to clarify please.
Do you remember if you tried to print brackets/results or anything which generated error in Arena prior to the "freeze"? I mean were there any error message (due to long running operations) in Arena admin before you started seeing the unresponsive state of Scoreboard and Arena admin interface?
-Dear Csabavirag;
The printing error generally occurs when we print 50 or more referee sheets. I took the screenshots of Csabavirag. We have to print the matches one by one. This takes a long time. For example - between 1-20 and 20-30.
![Ekran Görüntüsü (54)](https://user-images.githubusercontent.com/79795576/164997409-dec0b583-e844-48f0-ada5-f9fa53b04a0e.png)
![Ekran Görüntüsü (55)](https://user-images.githubusercontent.com/79795576/164997411-d35f9cf3-23e4-41a7-b380-f0f655c9dbf1.png)
![Ekran Görüntüsü (53)](https://user-images.githubusercontent.com/79795576/164997412-0cd43a1c-a706-4834-bb55-030130554163.png)

**Comment by dkaya60** [comment]
@dkaya60 thanks for the details. One more thing to clarify please.
Do you remember if you tried to print brackets/results or anything which generated error in Arena prior to the "freeze"? I mean were there any error message (due to long running operations) in Arena admin before you started seeing the unresponsive state of Scoreboard and Arena admin interface?

-Csabavırag ,While sending a match to the main server using the scoreboard program from the referee tables, I did not observe any printing errors. As I said before, we cannot send a match from the referee tables in the competitions with a HIGH NUMBER of ATHLETES. ARENA gets locked.I don't think it has anything to do with the RAM or CPU of the computer. I think ARENA should develop softwareI don't think it has anything to do with the RAM or CPU of the computer. I think ARENA should develop software

**Comment by csabavirag** [comment]
@dkaya60 Please validate your use case with Arena version 1.5.81. There are improvements for large events.

**Comment by dkaya60** [comment]
Thank You Csaba.
