### ISSUE TITLE
Identifier for categories that already finished

### ISSUE THREAD

**Issue by palvespt** [unitedworldwrestling/arena-public#82]
Hi Arena Team,

Is it possible to add an identifier to the weight categories that already finished?
With a lot of categories on the same day, its difficult to manage those that already finished and are ready for the medals cerimony, while the competition is still in progress.
Please check the image and  some ideas below.
1 = same colour as 2, or another colour
3= if the finals are completed , please add completed or finished next the rankings links
Or any other method/idea.

Thanks in advance for your support.
Pedro

![categories](https://user-images.githubusercontent.com/94856801/163897612-3a4effa2-c73e-4008-a912-1b57e3964c0a.JPG)

**Comment by csabavirag** [comment]
Hi Pedro,

Thanks for the suggestions. You should expect to see the following changes starting from the next version (>1.5.80):
- having a green star for weights with all their fights completed
![image](https://user-images.githubusercontent.com/10976654/165235992-c7b4cdd4-277d-4a12-9abe-41436e19098a.png)
- no Ranking option available to weight categories having open fights
![image](https://user-images.githubusercontent.com/10976654/165236267-9996a315-2d61-48bd-ba2d-19d8aabbe437.png)

**Comment by palvespt** [comment]
Hi Csaba,

This is great news.
Looking forward to try it on our next competition.
Many thanks for your support!

**Comment by csabavirag** [comment]
available in 1.5.81
