### ISSUE TITLE
Arena is currently in maintenance

### ISSUE THREAD

**Issue by Oralkhan55** [unitedworldwrestling/arena-public#84]
Hello!

When you click to update "Arena is currently in maintenance"

Performed the following steps as instructed:

during the upgrade I get the message "ERROR: Failed to install faucet". To fix the error, follow these steps:
Uploaded the arena_upgrade file for the operating system running Arena.
Arena has been launched and is available via http://localhost:8080.
Opened Windows Command Prompt.
Ran arena_upgrade from download folder.
Waited for the update to complete.

As a result, the Arena does not start "Arena is currently in maintenance".
We are planning an event on April 30, 2022, please hurry up if there is a solution, thank you in advance!

**Comment by csabavirag** [comment]
Please try the upgrade with a fresh VM install. Does it fail as well?

**Comment by Oralkhan55** [comment]
Yes, I tried it, it does not work.

**Comment by Oralkhan55** [comment]
Can you log into my computer remotely via TeamViewer and fix it?

ID: 1 417 123 409
password: 5kck665d

**Comment by csabavirag** [comment]
I am sorry, but can't do remote access right today.
But I just tested, downloaded the latest 1.5.71.1 VM image and the upgrade was successful. Please download it (again) from the main page (https://github.com/unitedworldwrestling/arena-public) and try to upgrade. It must work.

**Comment by csabavirag** [comment]
@Oralkhan55 were you able to upgrade the VM? If you still need remote assistance, please email the TeamViewer details to UWW IT email address (do not share it publicly)

**Comment by csabavirag** [comment]
I assume the issue has been fixed.

**Comment by Oralkhan55** [comment]
Hello!  Yes, thanks, the issue has been resolved.



Отправлено из мобильной Почты Mail.ru


четверг, 19 мая 2022 г., 13:52 +0600 от ***@***.***  ***@***.***>:
