### ISSUE TITLE
LGTV problem shuts down unexpectedly

### ISSUE THREAD

**Issue by gkaravitis** [unitedworldwrestling/arena-public#85]
**Which application you are experiencing a problem with**
LGTV

**Describe the bug**
I have downloaded the latest release in my streaming laptops. I am trying to access my scoreboard pcs but when I put  in repsectively field the pcs local ip eg. 192.168.3.122 and pressing Start LGTV button a green screen appears and then the application is shutting down.

I found a trace txt file thath I am attaching 

Thanks in advance,

Desktop (please complete the following information):**
 - OS: Windows 10
 - Stream software Vmix.
[trace.log](https://github.com/unitedworldwrestling/arena-public/files/8687012/trace.log)

**Comment by gkaravitis** [comment]
Updating the status of this issue:
By using this old https://we.tl/t-GysVJKuk1c version of LGTV the connection with the scoreboard pcs is ok and running with no issues. 

The error persist with the latest LGTV application running the latest version of arena and scoreboard application.

If you have any insights how to manage to run the new release i will be gratefull.

**Comment by gkaravitis** [comment]
Is there any updates on this issue?

**Comment by csabavirag** [comment]
Hello George, sorry for the late response. Could you please collect some logs from Windows Event Viewer application? You must search the crash log under Event Viewer->Windows logs->Application section. Please try to reproduce the crash then it will be at the top of the list.
We need the details of the error (where the source is the LGTV Responsive.exe).
Just paste the details here.

**Comment by Oralkhan55** [comment]
Hello! When launching LGTV in the OBS studio, the scene does not come out, please tell me what is the reason for this?

**Comment by gkaravitis** [comment]
@csabavirag Sorry for the late repsonse but i havent had the time to get back to you. I have just reproduce the issue and I am attaching the log from the windows event logger. 
`United World Wrestling - LGTV Responsive.exe 
   1.2.6.0 
   623ee248 
   KERNELBASE.dll 
   10.0.19041.2251 
   0d929ca0 
   e0434352 
   0012e062 
   44c8 
   01d8fb88756c9e61 
   C:\Program Files (x86)\United World Wrestling - LGTV Responsive\United World Wrestling - LGTV Responsive.exe 
   C:\windows\System32\KERNELBASE.dll 
   8759cb15-4c44-4ebf-80c2-bfe578ee38af 
`

Thanks in advance.

**Comment by csabavirag** [comment]
@gkaravitis would you mind reproducing the issue with the latest version of LGTV? Please detail the steps how you could reproduce the crash and attach the trace log generated by the latest version.
That would help recreating the error on our side and find the root cause.

Thanks!!

**Comment by gkaravitis** [comment]
I am very sorry for my late response. We havent had matches for a long period of time. I am attaching you the error log with the latest LGTV version and the latest Scoreboard. Sorry but my machine is in Greek.

`Όνομα αρχείου καταγραφής:Application
Προέλευση:     .NET Runtime
Ημερομηνία:    11/3/2023 11:24:13 πμ
Αναγνωριστικό συμβάντος:1026
Κατηγορία εργασιών:Καμία
Επίπεδο:       Σφάλμα
Λέξεις-κλειδιά:Κλασική
Χρήστης:       Δ/Υ
Υπολογιστής:   DESKTOP-KFBHT8N
Περιγραφή:
Εφαρμογή: United World Wrestling - LGTV Responsive.exe
Έκδοση Framework: v4.0.30319
Περιγραφή: Η διεργασία τερματίστηκε λόγω μιας εξαίρεσης που δεν αντιμετωπίστηκε.
Πληροφορίες εξαίρεσης: System.IndexOutOfRangeException
   σε uww_lgtv.Responsive.SetCode()
   σε uww_lgtv.Responsive+<DFStartMatch>d__46.MoveNext()
   σε System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   σε System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   σε System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   σε System.Windows.Threading.DispatcherOperation.InvokeImpl()
   σε MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   σε System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   σε System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   σε System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   σε MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   σε System.Windows.Threading.DispatcherOperation.Invoke()
   σε System.Windows.Threading.Dispatcher.ProcessQueue()
   σε System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   σε MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   σε MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   σε System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   σε System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   σε System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   σε MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   σε MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   σε System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   σε System.Windows.Application.RunDispatcher(System.Object)
   σε System.Windows.Application.RunInternal(System.Windows.Window)
   σε uww_lgtv.App.Main()


Xml συμβάντος:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-03-11T09:24:13.094305800Z" />
    <EventRecordID>36095</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-KFBHT8N</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Εφαρμογή: United World Wrestling - LGTV Responsive.exe
Έκδοση Framework: v4.0.30319
Περιγραφή: Η διεργασία τερματίστηκε λόγω μιας εξαίρεσης που δεν αντιμετωπίστηκε.
Πληροφορίες εξαίρεσης: System.IndexOutOfRangeException
   σε uww_lgtv.Responsive.SetCode()
   σε uww_lgtv.Responsive+&lt;DFStartMatch&gt;d__46.MoveNext()
   σε System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   σε System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   σε System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   σε System.Windows.Threading.DispatcherOperation.InvokeImpl()
   σε MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   σε System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   σε System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   σε System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   σε MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   σε System.Windows.Threading.DispatcherOperation.Invoke()
   σε System.Windows.Threading.Dispatcher.ProcessQueue()
   σε System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   σε MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   σε MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   σε System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   σε System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   σε System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   σε MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   σε MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   σε System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   σε System.Windows.Application.RunDispatcher(System.Object)
   σε System.Windows.Application.RunInternal(System.Windows.Window)
   σε uww_lgtv.App.Main()

</Data>
  </EventData>
</Event>`

**Comment by prosfygas33** [comment]
Hello, is there any update on this issue?

**Comment by bouaziz1991** [comment]
Dear @csabavirag ,

Can you please send us an email on it@uww.org to have a TeamViewer session, I need to check more closer this issue,

Best regards.
