### ISSUE TITLE
Total number of the athletes per competition and per categorie

### ISSUE THREAD

**Issue by palvespt** [unitedworldwrestling/arena-public#86]
Dear Arena Team,

If possible i would like to request to add the total number of the athletes per competition and per categorie.

This would help us a lot on our competitions.

How?

I upload all the athletes per competition by an excel file to speed up the process (moving athletes between categories and deletions of athletes which also will delete categories if they are empty).

However after the upload i need to count one by one to be sure that all athletes from the excel file were uploaded.

So, the ideia was to have something similar like this:
![athlets number](https://user-images.githubusercontent.com/94856801/168401590-d5de75fd-a1dd-4317-9c6d-e052322774d0.JPG)

In addition the total number of athletes per categorie would also help us a lot because with this, we can automatically know the number of matches per categorie (e.g 3 athletes = 3 matches).

Please also check this image: 

![athletes per category](https://user-images.githubusercontent.com/94856801/168401542-eba88d34-938b-46c7-a593-84e4d8ef6d86.JPG)

Thanks for your support.
Pedro Alves

**Comment by csabavirag** [comment]
@palvespt Could you please check Arena version 1.5.82 and let us know if the new feature is helpful to you?

**Comment by palvespt** [comment]
Hi @csabavirag,
Sry the late answer.
Indeed its great and very helpful.
In the future and if possible, please also add the number of athletes on the athletes page, like the prtscr above.
This will also save time to verify the total number of athletes per competition after the excel upload.

Thanks for your support!

**Comment by csabavirag** [comment]
Number of athletes is available on the weight category page as well.

**Comment by palvespt** [comment]
Amazing support.
Thanks!
