### ISSUE TITLE
Custom Logo on  pdf sheets exporting and bracket overlapping texts

### ISSUE THREAD

**Issue by prosfygas33** [unitedworldwrestling/arena-public#91]
**Which application you are interested about**
Arena

**Your question**
Hello i would like to ask if it is possible to insert our logo in pdf sheets as the example in the photo.

![Screenshot_1](https://user-images.githubusercontent.com/52703745/169269179-b39d3e2b-5b6f-4870-8496-2e49fc6980e3.jpg)

And the second question how can i avoid having overlapping names due to character length on bracket pdf . See the attachment

![Screenshot_3](https://user-images.githubusercontent.com/52703745/169280240-3b76bcbd-c52a-4ee6-bd60-4cbcb8c1f0a0.jpg)

**Comment by csabavirag** [comment]
Arena does not support changing the custom logo for a sport event through the web interface. Thus you can't replace the UWW one.

With regards to the bracket, there is a limited area to draw the bracket, therefore the length of the names are also limited. The original design was only considered to the 3 digit team names (which is much longer in your case), however long athlete names neither fits in even if you have a few characters long team name.

Let's keep this issue open and we will look into both questions and prioritise the development for them.

**Comment by csabavirag** [comment]
Hi, custom logo feature will be available in the next Arena version.
