### ISSUE TITLE
Arena-bracket dont showing Name of athletes

### ISSUE THREAD

**Issue by prosfygas33** [unitedworldwrestling/arena-public#94]
Arena
Hello i would like to ask how is it possible in bracket of beach wrestling event showing the birth date of an athlete and not the full name as the example in the photo. How can i fix this?? The group above it is correct.

![Screenshot_3](https://user-images.githubusercontent.com/52703745/175908907-503f3335-e472-456d-a386-6be7e31ca022.jpg)

**Comment by csabavirag** [comment]
Hi, while you can see the "full name" of the athletes in the group phase (top half of the screenshot), the "displayname" attribute is used for the bracket (bottom half with SemiFinal and Gold rounds). So please check the persons' details (People -> Search -> select a person and Edit) and you can modify the "Display name" attribute.

**Comment by csabavirag** [comment]
@prosfygas33 do you have an update on this? Were you able to fix the problem by setting up the DisplayName attribute of the athletes?

**Comment by prosfygas33** [comment]
@csabavirag  Yes,  thanks for your help.
