### ISSUE TITLE
Disruption in team competitions

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#95]
Hello
In team competitions, if we change the order of the competitions after the competition, the whole competition will be disrupted. Please checK.
![Disruption in team competitions](https://user-images.githubusercontent.com/82810245/179904058-2aa86ef0-2331-492f-b873-b86b2a4f86dc.jpg)

**Comment by mostafaaghayari** [comment]
https://user-images.githubusercontent.com/82810245/179907629-81e909bc-1ed7-4ff7-bd5b-812465f332fe.mp4

**Comment by csabavirag** [comment]
@mostafaaghayari finally I was able to reproduce the problem. It was not that straight forward, because it worked fine during the tests.
You should expect a fix in the next version

**Comment by mostafaaghayari** [comment]
Hi I thank the IT group and Mr csabavirag.

**Comment by mostafaaghayari** [comment]
Hello
Thank you dear csaba, the error has been fixed.

**Comment by mostafaaghayari** [comment]
.Hello
Thank you dear csaba, the error has been fixed.
