### ISSUE TITLE
Sortnig in entry list

### ISSUE THREAD

**Issue by theswix** [unitedworldwrestling/arena-public#98]
**In which application you miss a feature**
Arena 1.5.83.1

**Is your feature request related to a problem? Please describe.**
During large events (e.g. - around 100 athletes in one weight class only) sometimes it is really hard to find the appropriate athlete in the entry list at the weigh-in procedure. It really takes a lot of time since the athletes are sorted in quite questionable way.

Here is the problem. May be it can be done by default Arena means, but I haven't found this yet :(

Please find attached two pdf files (I intentionally did not take large amount of athletes there so that it would be easier to deal with) and take a look e.g. at the last 4 entries with the team name (ЯНА)- one file is entry list before the draw. The athletes there are sorted correctly in alphabetical order (in Russian in our case) by team name AND - within the team - by last name. Quite understandable so far (with minor glitch that I will explain later - just think what happens if we have, say, 10 Csaba, 10 Ivan and 10 Munhmainbayrpurevsaihantungalagsuhgombo - which is a real Mongolian name btw :) ).

Second file is after the draw. Athlets are sorted by teams in alphabetical order AND draw number. There is no sorting by last name already. Just imagine an situation where all the athletes (e.g. 100) are from one region and sorted by draw number. The weigh-in team will go crazy just looking for the athlete's name to make him sign the papers :) Because I bet that the last thing an athlete thinks about during the weigh-in is his draw number (in case if he were questioned about it by the weigh-in team in order to find him faster). Manual setting of different sorting type during printout would be of a great help in such a cases. And here is that glitch I mentioned earlier - even in almost ideal sorting before draw there should be a possibility to rely upon the last name and print it in reverse order i.e. LAST First.

**Describe the solution you'd like**
The possibility to sort the entry list before printout in different combinations. Suggesting the following:

- Draw number
- Team
- LAST First
- Team & Draw number
- Team & First LAST
- Team & LAST First

**Describe alternatives you've considered**
None

**Additional context**
Arean team does wonderful job with lot of patience to tolerate such obnoxious users as me :)

[entry_list_before_draw.pdf](https://github.com/unitedworldwrestling/arena-public/files/10029144/entry_list_before_draw.pdf)
[entry_list_after_draw.pdf](https://github.com/unitedworldwrestling/arena-public/files/10029145/entry_list_after_draw.pdf)
[test_seniors_57.xlsx](https://github.com/unitedworldwrestling/arena-public/files/10029676/test_seniors_57.xlsx)

**Comment by csabavirag** [comment]
You can find this feature starting from Arena version 1.5.84
