### ISSUE TITLE
Printing from main menu throws an exception

### ISSUE THREAD

**Issue by theswix** [unitedworldwrestling/arena-public#99]
Arena 1.5.83.1

**Describe the bug**
Attempting to print Team List, Participants List and Team Ranking from Arena main Print menu for one weight class only - 57 kg (http://localhost:8080/bracket/print/929ae787-6646-11ed-ab80-08002745f808) results in Arena exception with nginx errors 500, 500 and 404 respectively in case the checkbox "Freestyle (Seniors)" is empty.
Attempting to print the same info from weight category itself works as expected - pdf is generated.

**To Reproduce**
1. Import athletes (or take my db)
2. Make a draw in one weight class
3. Create matches
4. Go to print menu
5. Select only one weight class where you had a draw, and leave all the other checkboxes on the page unset
6. Try to print Team List, Participants List and Team Ranking
7. See errors on respective pages

If I check BOTH "Freestyle (Seniors)" and FS - 57 kg (Seniors) or "Select All", everything working as expected.

**Expected behavior**
Normal printing of requested items. 

If user should set the checkbox and ommited it by mistake, there should be a tip like "press the appropriate checkbox first" and NOT exception throwed since it is frustrating for most users and they start to panic :)

**Screenshots**
<img width="1065" alt="print_menu" src="https://user-images.githubusercontent.com/54967199/202400192-f2b79839-22a7-4492-bc62-62b78ed7d269.png">
<img width="842" alt="bracket_problem" src="https://user-images.githubusercontent.com/54967199/202400248-50104a5e-67e1-4d90-8887-2f00c7f0b2a5.png">
<img width="830" alt="entry_list_problem" src="https://user-images.githubusercontent.com/54967199/202400366-a348fd67-2fc9-4112-8068-6ab01d14231d.png">
<img width="828" alt="ranking_problem" src="https://user-images.githubusercontent.com/54967199/202400417-e7f9ca78-f2d1-4e46-9d7f-986ebf29dbb4.png">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.0.1 (also reproducible on  )
 - Browser FF 106.0.5
 - Version 106.0.5

**Additional context**
[dbdump_printing.sql.zip](https://github.com/unitedworldwrestling/arena-public/files/10029524/dbdump_printing.sql.zip)

**Comment by csabavirag** [comment]
Hi @theswix you are completely right, this page has a slightly weak UI experience, it should have notify you if you made a wrong selection. This will be fixed, no question :).
The reason why you received the error just because you chose a wrong selection. The action buttons you highlighted belong to the style selection (anything above the horizontal line). So if you chose "Freestyle (Seniors)" and then click on any of Participants table, Team List/Ranking, you should receive the PDF files according to your choice.

**Comment by theswix** [comment]
Fixed properly in beta
